export const HSK1 = [
  {
    chinese: "我",
    pinyin: "wǒ",
    meaning: "I, me",
    key: 1,
  },
  {
    chinese: "我们",
    pinyin: "wǒmen",
    meaning: "we, us (pl.)",
    key: 2,
  },
  {
    chinese: "你",
    pinyin: "nǐ",
    meaning: "you",
    key: 3,
  },
  {
    chinese: "你们",
    pinyin: "nǐmen",
    meaning: "you (pl.)",
    key: 4,
  },
  {
    chinese: "他",
    pinyin: "tā",
    meaning: "he, him",
    key: 5,
  },
  {
    chinese: "她",
    pinyin: "tā",
    meaning: "she, her",
    key: 6,
  },
  {
    chinese: "他们",
    pinyin: "tāmen",
    meaning: "they (male+female / male, pl.)",
    key: 7,
  },
  {
    chinese: "她们",
    pinyin: "tāmen",
    meaning: "they (females, pl.)",
    key: 8,
  },
  {
    chinese: "这 (这儿)",
    pinyin: "zhè ( zhèr)",
    meaning: "here, this",
    key: 9,
  },
  {
    chinese: "那 (那儿)",
    pinyin: "nà (nàr)",
    meaning: "there, that",
    key: 10,
  },
  {
    chinese: "哪（哪儿）",
    pinyin: "nǎ (nǎr)",
    meaning: "where",
    key: 11,
  },
  {
    chinese: "谁",
    pinyin: "shuí",
    meaning: "who",
    key: 12,
  },
  {
    chinese: "什么",
    pinyin: "shén me",
    meaning: "what, why",
    key: 13,
  },
  {
    chinese: "多少",
    pinyin: "duōshǎo",
    meaning: "how many, how much",
    key: 14,
  },
  {
    chinese: "几",
    pinyin: "jǐ",
    meaning: "a few, how many",
    key: 15,
  },
  {
    chinese: "怎么",
    pinyin: "zěnme",
    meaning: "how",
    key: 16,
  },
  {
    chinese: "怎么样",
    pinyin: "zěnmeyàng",
    meaning: "how about",
    key: 17,
  },
  {
    chinese: "一",
    pinyin: "yī",
    meaning: "one",
    key: 18,
  },
  {
    chinese: "二",
    pinyin: "èr",
    meaning: "two",
    key: 19,
  },
  {
    chinese: "三",
    pinyin: "sān",
    meaning: "three",
    key: 20,
  },
  {
    chinese: "四",
    pinyin: "sì",
    meaning: "four",
    key: 21,
  },
  {
    chinese: "五",
    pinyin: "wǔ",
    meaning: "five",
    key: 22,
  },
  {
    chinese: "六",
    pinyin: "liù",
    meaning: "six",
    key: 23,
  },
  {
    chinese: "七",
    pinyin: "qī",
    meaning: "seven",
    key: 24,
  },
  {
    chinese: "八",
    pinyin: "bā",
    meaning: "eight",
    key: 25,
  },
  {
    chinese: "九",
    pinyin: "jiǔ",
    meaning: "nine",
    key: 26,
  },
  {
    chinese: "十",
    pinyin: "shí",
    meaning: "ten",
    key: 27,
  },
  {
    chinese: "零",
    pinyin: "líng",
    meaning: "zero",
    key: 28,
  },
  {
    chinese: "个",
    pinyin: "gè",
    meaning: "one, a, an",
    key: 29,
  },
  {
    chinese: "岁",
    pinyin: "suì",
    meaning: "year",
    key: 30,
  },
  {
    chinese: "本",
    pinyin: "běn",
    meaning: "volume",
    key: 31,
  },
  {
    chinese: "些",
    pinyin: "xiē",
    meaning: "some",
    key: 32,
  },
  {
    chinese: "块",
    pinyin: "kuài",
    meaning: "piece",
    key: 33,
  },
  {
    chinese: "不",
    pinyin: "bù",
    meaning: "no",
    key: 34,
  },
  {
    chinese: "没",
    pinyin: "méi",
    meaning: "no",
    key: 35,
  },
  {
    chinese: "很",
    pinyin: "hěn",
    meaning: "quite, very",
    key: 36,
  },
  {
    chinese: "太",
    pinyin: "tài",
    meaning: "too",
    key: 37,
  },
  {
    chinese: "都",
    pinyin: "dōu",
    meaning: "all",
    key: 38,
  },
  {
    chinese: "和",
    pinyin: "hé",
    meaning: "and",
    key: 39,
  },
  {
    chinese: "在",
    pinyin: "zài",
    meaning: "in, at",
    key: 40,
  },
  {
    chinese: "的",
    pinyin: "de",
    meaning: "",
    key: 41,
  },
  {
    chinese: "了",
    pinyin: "le",
    meaning: "",
    key: 42,
  },
  {
    chinese: "吗",
    pinyin: "ma",
    meaning: "",
    key: 43,
  },
  {
    chinese: "呢",
    pinyin: "ne",
    meaning: "",
    key: 44,
  },
  {
    chinese: "喂",
    pinyin: "wèi",
    meaning: "hello",
    key: 45,
  },
  {
    chinese: "家",
    pinyin: "jiā",
    meaning: "home",
    key: 46,
  },
  {
    chinese: "学校",
    pinyin: "xuéxiào",
    meaning: "school",
    key: 47,
  },
  {
    chinese: "饭店",
    pinyin: "fàndiàn",
    meaning: "restaurant",
    key: 48,
  },
  {
    chinese: "商店",
    pinyin: "shāngdiàn",
    meaning: "store",
    key: 49,
  },
  {
    chinese: "医院",
    pinyin: "yīyuàn",
    meaning: "hospital",
    key: 50,
  },
  {
    chinese: "火车站",
    pinyin: "huǒchēzhàn",
    meaning: "train station",
    key: 51,
  },
  {
    chinese: "中国",
    pinyin: "zhōng guó",
    meaning: "China",
    key: 52,
  },
  {
    chinese: "北京",
    pinyin: "běijīng",
    meaning: "Beijing",
    key: 53,
  },
  {
    chinese: "上",
    pinyin: "shàng",
    meaning: "up",
    key: 54,
  },
  {
    chinese: "下",
    pinyin: "xià",
    meaning: "down",
    key: 55,
  },
  {
    chinese: "前面",
    pinyin: "qiánmiàn",
    meaning: "front",
    key: 56,
  },
  {
    chinese: "后面",
    pinyin: "hòumiàn",
    meaning: "behind",
    key: 57,
  },
  {
    chinese: "里",
    pinyin: "lǐmiàn",
    meaning: "inside",
    key: 58,
  },
  {
    chinese: "今天",
    pinyin: "jīntiān",
    meaning: "today",
    key: 59,
  },
  {
    chinese: "明天",
    pinyin: "míngtiān",
    meaning: "tomorrow",
    key: 60,
  },
  {
    chinese: "昨天",
    pinyin: "zuótiān",
    meaning: "yesterday",
    key: 61,
  },
  {
    chinese: "上午",
    pinyin: "shàngwǔ",
    meaning: "morning",
    key: 62,
  },
  {
    chinese: "中午",
    pinyin: "zhōngwǔ",
    meaning: "noon",
    key: 63,
  },
  {
    chinese: "下午",
    pinyin: "xiàwǔ",
    meaning: "afternoon",
    key: 64,
  },
  {
    chinese: "年",
    pinyin: "nián",
    meaning: "year",
    key: 65,
  },
  {
    chinese: "月",
    pinyin: "yuè",
    meaning: "month",
    key: 66,
  },
  {
    chinese: "日",
    pinyin: "rì",
    meaning: "day",
    key: 67,
  },
  {
    chinese: "星期",
    pinyin: "xīngqī",
    meaning: "week",
    key: 68,
  },
  {
    chinese: "点",
    pinyin: "diǎn",
    meaning: "dot, spot",
    key: 69,
  },
  {
    chinese: "分钟",
    pinyin: "fēnzhōng",
    meaning: "minute",
    key: 70,
  },
  {
    chinese: "现在",
    pinyin: "xiànzài",
    meaning: "now",
    key: 71,
  },
  {
    chinese: "时候",
    pinyin: "shíhou",
    meaning: "time",
    key: 72,
  },
  {
    chinese: "爸爸",
    pinyin: "bàba",
    meaning: "father",
    key: 73,
  },
  {
    chinese: "妈妈",
    pinyin: "māma",
    meaning: "mother",
    key: 74,
  },
  {
    chinese: "儿子",
    pinyin: "érzi",
    meaning: "son",
    key: 75,
  },
  {
    chinese: "女儿",
    pinyin: "nǚér",
    meaning: "daughter",
    key: 76,
  },
  {
    chinese: "老师",
    pinyin: "lǎoshī",
    meaning: "teacher",
    key: 77,
  },
  {
    chinese: "学生",
    pinyin: "xuéshēng",
    meaning: "student",
    key: 78,
  },
  {
    chinese: "同学",
    pinyin: "tóngxué",
    meaning: "shoolmate",
    key: 79,
  },
  {
    chinese: "朋友",
    pinyin: "péngyou",
    meaning: "friend",
    key: 80,
  },
  {
    chinese: "医生",
    pinyin: "yīshēng",
    meaning: "doctor",
    key: 81,
  },
  {
    chinese: "先生",
    pinyin: "xiānsheng",
    meaning: "sir",
    key: 82,
  },
  {
    chinese: "小姐",
    pinyin: "xiǎojiě",
    meaning: "Miss",
    key: 83,
  },
  {
    chinese: "衣服",
    pinyin: "yīfu",
    meaning: "cloth",
    key: 84,
  },
  {
    chinese: "水",
    pinyin: "shuǐ",
    meaning: "water",
    key: 85,
  },
  {
    chinese: "菜",
    pinyin: "cài",
    meaning: "vegetable",
    key: 86,
  },
  {
    chinese: "米饭",
    pinyin: "mǐfàn",
    meaning: "rice",
    key: 87,
  },
  {
    chinese: "水果",
    pinyin: "shuǐguǒ",
    meaning: "fruit",
    key: 88,
  },
  {
    chinese: "苹果",
    pinyin: "píngguǒ",
    meaning: "apple",
    key: 89,
  },
  {
    chinese: "茶",
    pinyin: "chá",
    meaning: "tea",
    key: 90,
  },
  {
    chinese: "杯子",
    pinyin: "bēizi",
    meaning: "cup",
    key: 91,
  },
  {
    chinese: "钱",
    pinyin: "qián",
    meaning: "money",
    key: 92,
  },
  {
    chinese: "飞机",
    pinyin: "fēijī",
    meaning: "airplane",
    key: 93,
  },
  {
    chinese: "出租车",
    pinyin: "chūzūchē",
    meaning: "taxi",
    key: 94,
  },
  {
    chinese: "电视",
    pinyin: "diànshì",
    meaning: "television",
    key: 95,
  },
  {
    chinese: "电脑",
    pinyin: "diànnǎo",
    meaning: "computer",
    key: 96,
  },
  {
    chinese: "电影",
    pinyin: "diànyǐng",
    meaning: "movie",
    key: 97,
  },
  {
    chinese: "天气",
    pinyin: "tiānqì",
    meaning: "weather",
    key: 98,
  },
  {
    chinese: "猫",
    pinyin: "māo",
    meaning: "cat",
    key: 99,
  },
  {
    chinese: "狗",
    pinyin: "gǒu",
    meaning: "dog",
    key: 100,
  },
  {
    chinese: "东西",
    pinyin: "dōngxi",
    meaning: "thing",
    key: 101,
  },
  {
    chinese: "人",
    pinyin: "rén",
    meaning: "person",
    key: 102,
  },
  {
    chinese: "名字",
    pinyin: "míngzi",
    meaning: "name",
    key: 103,
  },
  {
    chinese: "书",
    pinyin: "shū",
    meaning: "book",
    key: 104,
  },
  {
    chinese: "汉语",
    pinyin: "hànyǔ",
    meaning: "mandarin chinese",
    key: 105,
  },
  {
    chinese: "字",
    pinyin: "zì",
    meaning: "character",
    key: 106,
  },
  {
    chinese: "桌子",
    pinyin: "zhuōzi",
    meaning: "desk",
    key: 107,
  },
  {
    chinese: "椅子",
    pinyin: "yǐzi",
    meaning: "chair",
    key: 108,
  },
  {
    chinese: "Verb",
    pinyin: "",
    meaning: "",
    key: 109,
  },
  {
    chinese: "谢谢",
    pinyin: "xièxie",
    meaning: "thank",
    key: 110,
  },
  {
    chinese: "不客气",
    pinyin: "búkèqì",
    meaning: "you are welcome",
    key: 111,
  },
  {
    chinese: "再见",
    pinyin: "zàijiàn",
    meaning: "good-bye",
    key: 112,
  },
  {
    chinese: "请",
    pinyin: "qǐng",
    meaning: "please",
    key: 113,
  },
  {
    chinese: "对不起",
    pinyin: "duìbùqǐ",
    meaning: "sorry",
    key: 114,
  },
  {
    chinese: "没关系",
    pinyin: "méiguānxì",
    meaning: "It doesn’t matter",
    key: 115,
  },
  {
    chinese: "是",
    pinyin: "shì",
    meaning: "be (am, is, are)",
    key: 116,
  },
  {
    chinese: "有",
    pinyin: "yǒu",
    meaning: "have",
    key: 117,
  },
  {
    chinese: "看",
    pinyin: "kàn",
    meaning: "look",
    key: 118,
  },
  {
    chinese: "听",
    pinyin: "tīng",
    meaning: "listen",
    key: 119,
  },
  {
    chinese: "说话",
    pinyin: "shuōhuà",
    meaning: "speak",
    key: 120,
  },
  {
    chinese: "读",
    pinyin: "dú",
    meaning: "read",
    key: 121,
  },
  {
    chinese: "写",
    pinyin: "xiě",
    meaning: "write",
    key: 122,
  },
  {
    chinese: "看见",
    pinyin: "kànjiàn",
    meaning: "see",
    key: 123,
  },
  {
    chinese: "叫",
    pinyin: "jiào",
    meaning: "call",
    key: 124,
  },
  {
    chinese: "来",
    pinyin: "lái",
    meaning: "come",
    key: 125,
  },
  {
    chinese: "回",
    pinyin: "huí",
    meaning: "return",
    key: 126,
  },
  {
    chinese: "去",
    pinyin: "qù",
    meaning: "go",
    key: 127,
  },
  {
    chinese: "吃",
    pinyin: "chī",
    meaning: "eat",
    key: 128,
  },
  {
    chinese: "喝",
    pinyin: "hē",
    meaning: "drink",
    key: 129,
  },
  {
    chinese: "睡觉",
    pinyin: "shuìjiào",
    meaning: "sleep",
    key: 130,
  },
  {
    chinese: "打电话",
    pinyin: "dǎdiànhuà",
    meaning: "call up",
    key: 131,
  },
  {
    chinese: "做",
    pinyin: "zuò",
    meaning: "do",
    key: 132,
  },
  {
    chinese: "买",
    pinyin: "mǎi",
    meaning: "buy",
    key: 133,
  },
  {
    chinese: "开",
    pinyin: "kāi",
    meaning: "open",
    key: 134,
  },
  {
    chinese: "坐",
    pinyin: "zuò",
    meaning: "sit",
    key: 135,
  },
  {
    chinese: "住",
    pinyin: "zhù",
    meaning: "live",
    key: 136,
  },
  {
    chinese: "学习",
    pinyin: "xuéxí",
    meaning: "study",
    key: 137,
  },
  {
    chinese: "工作",
    pinyin: "gōngzuò",
    meaning: "work",
    key: 138,
  },
  {
    chinese: "下雨",
    pinyin: "xiàyǔ",
    meaning: "rain",
    key: 139,
  },
  {
    chinese: "爱",
    pinyin: "ài",
    meaning: "love",
    key: 140,
  },
  {
    chinese: "喜欢",
    pinyin: "xǐhuān",
    meaning: "love, like",
    key: 141,
  },
  {
    chinese: "想",
    pinyin: "xiǎng",
    meaning: "want",
    key: 142,
  },
  {
    chinese: "认识",
    pinyin: "rènshi",
    meaning: "know",
    key: 143,
  },
  {
    chinese: "会",
    pinyin: "huì",
    meaning: "can",
    key: 144,
  },
  {
    chinese: "能",
    pinyin: "néng",
    meaning: "can, be able to",
    key: 145,
  },
  {
    chinese: "好",
    pinyin: "hǎo",
    meaning: "good",
    key: 146,
  },
  {
    chinese: "大",
    pinyin: "dà",
    meaning: "big",
    key: 147,
  },
  {
    chinese: "小",
    pinyin: "xiǎo",
    meaning: "small",
    key: 148,
  },
  {
    chinese: "多",
    pinyin: "duō",
    meaning: "many, much",
    key: 149,
  },
  {
    chinese: "少",
    pinyin: "shǎo",
    meaning: "few, little",
    key: 150,
  },
  {
    chinese: "冷",
    pinyin: "lěng",
    meaning: "cold",
    key: 151,
  },
  {
    chinese: "热",
    pinyin: "rè",
    meaning: "hot",
    key: 152,
  },
  {
    chinese: "高兴",
    pinyin: "gāoxìng",
    meaning: "happy",
    key: 153,
  },
  {
    chinese: "漂亮",
    pinyin: "piàoliàng",
    meaning: "beautiful",
    key: 154,
  },
];
