export const HSK6 = [
  {
    pinyin: "jiǔ xí",
    chinese: "酒席",
    meaning: "(Chinese style) banquet",
    page: 47,
    key: 1,
  },
  {
    pinyin: "xīn niáng",
    chinese: "新娘",
    meaning: "bride",
    page: 47,
    key: 2,
  },
  {
    pinyin: "xīn láng",
    chinese: "新郎",
    meaning: "bridegroom",
    page: 47,
    key: 3,
  },
  {
    pinyin: "jiàn zhù",
    chinese: "建筑",
    meaning: "building/architecture",
    page: 47,
    key: 4,
  },
  {
    pinyin: "wén zì",
    chinese: "文字",
    meaning: "characters or words (of a language)",
    page: 47,
    key: 5,
  },
  {
    pinyin: "yuǎn yuan",
    chinese: "远远",
    meaning:
      "far (as an advarb to mean either from a great distance or very much in a comparison)",
    page: 47,
    key: 6,
  },
  {
    pinyin: "xíng shì",
    chinese: "形式",
    meaning:
      "form (refers to a particular way in which a thing exists or appears)/formality (refers to something done merely for form's sake)",
    page: 47,
    key: 7,
  },
  {
    pinyin: "lè qù",
    chinese: "乐趣",
    meaning: "Fun (refers to enjoyment) (formal)",
    page: 47,
    key: 8,
  },
  {
    pinyin: "fú zhuāng",
    chinese: "服装",
    meaning: "Garment (more formal than 衣服yī fu)",
    page: 47,
    key: 9,
  },
  {
    pinyin: "wǎn ān",
    chinese: "晚安",
    meaning: "good night",
    page: 47,
    key: 10,
  },
  {
    pinyin: "yí bèizi",
    chinese: "一辈子",
    meaning: "lifetime",
    page: 47,
    key: 11,
  },
  {
    pinyin: "chāo piào",
    chinese: "钞票",
    meaning: "money (informal)/paper money",
    page: 47,
    key: 12,
  },
  {
    pinyin: "yè wǎn",
    chinese: "夜晚",
    meaning: "Night (more poetic than 晚上wǎn shàng)",
    page: 47,
    key: 13,
  },
  {
    pinyin: "kāi chǎng bái",
    chinese: "开场白",
    meaning: "opening remark",
    page: 47,
    key: 14,
  },
  {
    pinyin: "bā chéng",
    chinese: "八成",
    meaning: "probably (informal)/eighty percent",
    page: 47,
    key: 15,
  },
  {
    pinyin: "mù dì",
    chinese: "目的",
    meaning: "purpose",
    page: 47,
    key: 16,
  },
  {
    pinyin: "bèi zi",
    chinese: "被子",
    meaning: "quilt",
    page: 47,
    key: 17,
  },
  {
    pinyin: "hóng bāo",
    chinese: "红包",
    meaning: "red envelope",
    page: 47,
    key: 18,
  },
  {
    pinyin: "qǐ bù jià",
    chinese: "起步价",
    meaning: "starting price",
    page: 47,
    key: 19,
  },
  {
    pinyin: "jiāo qū",
    chinese: "郊区",
    meaning: "suburb",
    page: 47,
    key: 20,
  },
  {
    pinyin: "fēn xī",
    chinese: "分析",
    meaning: "to analyze/analysis",
    page: 47,
    key: 21,
  },
  {
    pinyin: "què dìng",
    chinese: "确定",
    meaning:
      "To be certain (about something) (more formal than 肯定kěn dìng)/to make certain or decide on",
    page: 47,
    key: 22,
  },
  {
    pinyin: "tán liàn'ài",
    chinese: "谈恋爱",
    meaning: "to be dating",
    page: 47,
    key: 23,
  },
  {
    pinyin: "shǎo yú",
    chinese: "少于",
    meaning: "To be less than (formal)",
    page: 47,
    key: 24,
  },
  {
    pinyin: "duō yú",
    chinese: "多于",
    meaning: "To be more than (fomral)",
    page: 47,
    key: 25,
  },
  {
    pinyin: "liú xíng",
    chinese: "流行",
    meaning: "to be popular (refers to prevalent)",
    page: 47,
    key: 26,
  },
  {
    pinyin: "rào wānzi",
    chinese: "绕弯子",
    meaning: "to beat around the bush (literally: to go on a long detour)",
    page: 47,
    key: 27,
  },
  {
    pinyin: "zào",
    chinese: "造",
    meaning: "to build/to create",
    page: 47,
    key: 28,
  },
  {
    pinyin: "zhù hè",
    chinese: "祝贺",
    meaning: "to congratulate/congratulation",
    page: 47,
    key: 29,
  },
  {
    pinyin: "shǔ",
    chinese: "数",
    meaning: "to count (amount of a number)",
    page: 47,
    key: 30,
  },
  {
    pinyin: "shè jì",
    chinese: "设计",
    meaning: "to design/design",
    page: 47,
    key: 31,
  },
  {
    pinyin: "wán bì",
    chinese: "完毕",
    meaning:
      "To finish (used after verbs with two characters like 执行zhí xíng to carry out 回答huí dá to answer 拍摄pāi shè to shoot (a film or photographs) 讨论tǎo lùn to discuss 准备zhǔn bèi to prepare 安装ān zhuāng to install (something) 创建chuàng jiàn to create 处理chù lǐ to handle or deal with 演讲yǎn jiǎng to make a speech 演奏yǎn zòu to give a performance with a musical instrument 印刷yìn shuā to print (in a large-scale industrial process) 修改xiū gǎi to revise or to amend 加工jiā gōng to process 使用shǐ yòng to use 鉴定jiàn dìng to appraise or authenticate (an object) 装修zhuāng xiū to renovate 销售xiāo shòu to sell 更新gēng xīn to renew or update 证明zhèng míng to prove 采访cǎi fǎng to interview 整理zhěng lǐ to put in order 调整tiáo zhěng to make adjustment 上传shàng chuán to upload 下载xià zǎi to download 翻译fān yì to translate) (more formal than 完了wán le)",
    page: 47,
    key: 32,
  },
  {
    pinyin: "qī dài",
    chinese: "期待",
    meaning: "to look forward to",
    page: 47,
    key: 33,
  },
  {
    pinyin: "pàn duàn",
    chinese: "判断",
    meaning:
      "to make a judgement/judgement (refers to an opinion formed by judging something)",
    page: 47,
    key: 34,
  },
  {
    pinyin: "hùn",
    chinese: "混",
    meaning: "to mix",
    page: 47,
    key: 35,
  },
  {
    pinyin: "rào",
    chinese: "绕",
    meaning: "to move around",
    page: 47,
    key: 36,
  },
  {
    pinyin: "bāo zhuāng",
    chinese: "包装",
    meaning: "to package/packaging",
    page: 47,
    key: 37,
  },
  {
    pinyin: "tuī lǐ",
    chinese: "推理",
    meaning: "to reason/reasoning",
    page: 47,
    key: 38,
  },
  {
    pinyin: "chāi",
    chinese: "拆",
    meaning: "to tear apart/to pull down",
    page: 47,
    key: 39,
  },
  {
    pinyin: "biàn",
    chinese: "便",
    meaning:
      "Used to modify nouns that come before it to give an impression of being a little, early or quick. (more formal than 就jiù)",
    page: 47,
    key: 40,
  },
  {
    pinyin: "sú",
    chinese: "俗",
    meaning: "vulgar",
    page: 47,
    key: 41,
  },
  {
    pinyin: "xī zhuāng",
    chinese: "西装",
    meaning: "(man's) suit",
    page: 48,
    key: 42,
  },
  {
    pinyin: "shí jì",
    chinese: "实际",
    meaning: "actual/actuality",
    page: 48,
    key: 43,
  },
  {
    pinyin: "rèn hé",
    chinese: "任何",
    meaning: "Any+noun+whatever or whichever (formal)",
    page: 48,
    key: 44,
  },
  {
    pinyin: "lěng jìng",
    chinese: "冷静",
    meaning: "calm (of a person)",
    page: 48,
    key: 45,
  },
  {
    pinyin: "rén xuǎn",
    chinese: "人选",
    meaning: "candidate",
    page: 48,
    key: 46,
  },
  {
    pinyin: "huá rén",
    chinese: "华人",
    meaning: "Chinese people (especially overseas Chinese) (formal)",
    page: 48,
    key: 47,
  },
  {
    pinyin: "mǎxì tuán",
    chinese: "马戏团",
    meaning: "circus",
    page: 48,
    key: 48,
  },
  {
    pinyin: "mèng",
    chinese: "梦",
    meaning: "dream",
    page: 48,
    key: 49,
  },
  {
    pinyin: "shǐ zhōng",
    chinese: "始终",
    meaning: "From beginning to end (keeping in a certain state) (formal)",
    page: 48,
    key: 50,
  },
  {
    pinyin: "zàng lǐ",
    chinese: "葬礼",
    meaning: "funeral",
    page: 48,
    key: 51,
  },
  {
    pinyin: "gāogēn xié",
    chinese: "高跟鞋",
    meaning: "high-heeled shoe",
    page: 48,
    key: 52,
  },
  {
    pinyin: "shì hòu",
    chinese: "事后",
    meaning: "hindsight",
    page: 48,
    key: 53,
  },
  {
    pinyin: "lǎ bā",
    chinese: "喇叭",
    meaning: "horn (in a automobile)/trumpet/loudspeaker",
    page: 48,
    key: 54,
  },
  {
    pinyin: "rán ér",
    chinese: "然而",
    meaning: "However (more formal than 不过bú guò)",
    page: 48,
    key: 55,
  },
  {
    pinyin: "bù miǎn",
    chinese: "不免",
    meaning: "inevitably",
    page: 48,
    key: 56,
  },
  {
    pinyin: "pí xié",
    chinese: "皮鞋",
    meaning: "leather shoe",
    page: 48,
    key: 57,
  },
  {
    pinyin: "fǎ guī",
    chinese: "法规",
    meaning: "legislation",
    page: 48,
    key: 58,
  },
  {
    pinyin: "xiūxián fú",
    chinese: "休闲",
    meaning:
      "leisure (时间shí jiān time 游戏yóu xì (recreational) game 食品shí pǐn food 活动huó dòng (group) activity 旅游lǚ yóu travel 购物gòu wù shopping 会所huì suǒ club 服装fú zhuāng garment)",
    page: 48,
    key: 59,
  },
  {
    pinyin: "xiūxián fú",
    chinese: "休闲服",
    meaning: "leisure clothes",
    page: 48,
    key: 60,
  },
  {
    pinyin: "zhí zhào",
    chinese: "执照",
    meaning:
      "license (营业执照yíngyè zhízhào business licence 驾驶执照jiàshǐ zhízhào driving license)",
    page: 48,
    key: 61,
  },
  {
    pinyin: "zhōng zhǐ",
    chinese: "中指",
    meaning: "middle finger",
    page: 48,
    key: 62,
  },
  {
    pinyin: "lǐng dài",
    chinese: "领带",
    meaning: "necktie",
    page: 48,
    key: 63,
  },
  {
    pinyin: "chǎng hé",
    chinese: "场合",
    meaning: "occasion (refers to specified social event)",
    page: 48,
    key: 64,
  },
  {
    pinyin: "huá qiáo",
    chinese: "华侨",
    meaning:
      "overseas Chinese (refers to Chinese citizen who resides outside of China)",
    page: 48,
    key: 65,
  },
  {
    pinyin: "huá yì",
    chinese: "华裔",
    meaning: "overseas Chinese (refers to foreign citizen of Chinese origin)",
    page: 48,
    key: 66,
  },
  {
    pinyin: "xiǎo qì",
    chinese: "小气",
    meaning: "petty (in character)/stingy",
    page: 48,
    key: 67,
  },
  {
    pinyin: "xīn lǐ",
    chinese: "心理",
    meaning: "psychology (refers to mentality)/psychological",
    page: 48,
    key: 68,
  },
  {
    pinyin: "xīnlǐ xué",
    chinese: "心理学",
    meaning: "psychology (refers to the scientific study)",
    page: 48,
    key: 69,
  },
  {
    pinyin: "tí mù",
    chinese: "题目",
    meaning: "Question (of homework or test) (more formal than 题tí)",
    page: 48,
    key: 70,
  },
  {
    pinyin: "ānquán dài",
    chinese: "安全带",
    meaning: "safety belt",
    page: 48,
    key: 71,
  },
  {
    pinyin: "xìn hào",
    chinese: "信号",
    meaning: "signal",
    page: 48,
    key: 72,
  },
  {
    pinyin: "mò shēng",
    chinese: "陌生",
    meaning: "Strange (refers to not known before) (formal)",
    page: 48,
    key: 73,
  },
  {
    pinyin: "shìjuàn",
    chinese: "试卷",
    meaning: "test paper",
    page: 48,
    key: 74,
  },
  {
    pinyin: "qián zhě",
    chinese: "前者",
    meaning: "the former",
    page: 48,
    key: 75,
  },
  {
    pinyin: "hòu zhě",
    chinese: "后者",
    meaning: "the latter",
    page: 48,
    key: 76,
  },
  {
    pinyin: "chū xí",
    chinese: "出席",
    meaning:
      "to attend (婚礼hūn lǐ wedding 会议huì yì conference/meeting (of a group of people for work) 葬礼zàng lǐ funeral 仪式yí shì rite 活动huó dòng event 开幕式kāimù shì opening ceremony)",
    page: 48,
    key: 77,
  },
  {
    pinyin: "hào sè",
    chinese: "好色",
    meaning: "to be lustful",
    page: 48,
    key: 78,
  },
  {
    pinyin: "duō xīn",
    chinese: "多心",
    meaning: "to be suspicious (of other people)",
    page: 48,
    key: 79,
  },
  {
    pinyin: "fán",
    chinese: "烦",
    meaning: "to bother/annoying/to be annoyed",
    page: 48,
    key: 80,
  },
  {
    pinyin: "shā chē",
    chinese: "刹车",
    meaning: "to brake/brake",
    page: 48,
    key: 81,
  },
  {
    pinyin: "shōu mǎi",
    chinese: "收买",
    meaning: "to buy over (refers to bribe)",
    page: 48,
    key: 82,
  },
  {
    pinyin: "pèi hé",
    chinese: "配合",
    meaning: "to cooperate/cooperation (by playing a supporting role)",
    page: 48,
    key: 83,
  },
  {
    pinyin: "qū bié",
    chinese: "区别",
    meaning: "to differentiate/difference",
    page: 48,
    key: 84,
  },
  {
    pinyin: "jià shǐ",
    chinese: "驾驶",
    meaning: "To drive (a transportation) (formal)",
    page: 48,
    key: 85,
  },
  {
    pinyin: "fáng",
    chinese: "防",
    meaning: "to guard against",
    page: 48,
    key: 86,
  },
  {
    pinyin: "zuò mèng",
    chinese: "做梦",
    meaning: "to have a dream",
    page: 48,
    key: 87,
  },
  {
    pinyin: "fàng guò",
    chinese: "放过",
    meaning: "to let off (somebody from punishment)",
    page: 48,
    key: 88,
  },
  {
    pinyin: "diǎn tóu",
    chinese: "点头",
    meaning: "to nod",
    page: 48,
    key: 89,
  },
  {
    pinyin: "chāo chē",
    chinese: "超车",
    meaning: "to overtake (another car)",
    page: 48,
    key: 90,
  },
  {
    pinyin: "fáng bèi",
    chinese: "防备",
    meaning:
      "to prepare and guard against (袭击xí jī surprise attack 事故shì gù accident 火灾huǒ zāi fire (as a disaster) 盗窃dào qiè theft)",
    page: 48,
    key: 91,
  },
  {
    pinyin: "shù",
    chinese: "竖",
    meaning: "to set upright",
    page: 48,
    key: 92,
  },
  {
    pinyin: "wēi xiào",
    chinese: "微笑",
    meaning: "to smile/smile",
    page: 48,
    key: 93,
  },
  {
    pinyin: "kāi chǎng",
    chinese: "开场",
    meaning: "to start (of a social event or stage performance)",
    page: 48,
    key: 94,
  },
  {
    pinyin: "jì",
    chinese: "系",
    meaning: "to tie (two ends of a lace, rope, etc)",
    page: 48,
    key: 95,
  },
  {
    pinyin: "kàn xì",
    chinese: "看戏",
    meaning: "to watch a play",
    page: 48,
    key: 96,
  },
  {
    pinyin: "gōng jù",
    chinese: "工具",
    meaning: "tool",
    page: 48,
    key: 97,
  },
  {
    pinyin: "bú duàn",
    chinese: "不断",
    meaning: "unceasing/unceasingly",
    page: 48,
    key: 98,
  },
  {
    pinyin: "hé shēn",
    chinese: "合身",
    meaning: "well-fitting (of clothes)",
    page: 48,
    key: 99,
  },
  {
    pinyin: "pái",
    chinese: "排",
    meaning: "to put in a row",
    page: 49,
    key: 100,
  },
  {
    pinyin: "qǔ",
    chinese: "娶",
    meaning: "(a man) to marry (to a woman)",
    page: 49,
    key: 101,
  },
  {
    pinyin: "zhǐ shì",
    chinese: "指示",
    meaning: "(a superior) to instruct/instruction",
    page: 49,
    key: 102,
  },
  {
    pinyin: "jià",
    chinese: "嫁",
    meaning: "(a woman) to marry (to a man)",
    page: 49,
    key: 103,
  },
  {
    pinyin: "biǎo qíng",
    chinese: "表情",
    meaning: "(facial) expression",
    page: 49,
    key: 104,
  },
  {
    pinyin: "wèi zhì",
    chinese: "位置",
    meaning: "(spatial) Position (more formal than 地方dì fang)",
    page: 49,
    key: 105,
  },
  {
    pinyin: "yàn shōu",
    chinese: "验收",
    meaning: "acceptance check",
    page: 49,
    key: 106,
  },
  {
    pinyin: "yǎn yuán",
    chinese: "演员",
    meaning: "actor/actress",
    page: 49,
    key: 107,
  },
  {
    pinyin: "shùn zhe",
    chinese: "顺着",
    meaning: "along (a direction, road or way)",
    page: 49,
    key: 108,
  },
  {
    pinyin: "xiāng yān",
    chinese: "香烟",
    meaning: "Cigarette (more formal than 烟yān)",
    page: 49,
    key: 109,
  },
  {
    pinyin: "bù jīn",
    chinese: "不禁",
    meaning: "Couldn't help but (do) (only used in the past) (formal)",
    page: 49,
    key: 110,
  },
  {
    pinyin: "qún",
    chinese: "群",
    meaning: "crowd/measure word for a crowd",
    page: 49,
    key: 111,
  },
  {
    pinyin: "fāng xiàng",
    chinese: "方向",
    meaning: "direction",
    page: 49,
    key: 112,
  },
  {
    pinyin: "tí qián",
    chinese: "提前",
    meaning:
      "Early (before the time which was arranged or expected) (more formal than 提早tí zǎo)",
    page: 49,
    key: 113,
  },
  {
    pinyin: "dà huǒr",
    chinese: "大伙儿",
    meaning: "everybody (less formal than 大家dà jiā)",
    page: 49,
    key: 114,
  },
  {
    pinyin: "biān pào",
    chinese: "鞭炮",
    meaning: "firecracker",
    page: 49,
    key: 115,
  },
  {
    pinyin: "yān huǒ",
    chinese: "烟火",
    meaning: "firework",
    page: 49,
    key: 116,
  },
  {
    pinyin: "jìn yíbù",
    chinese: "进一步",
    meaning:
      "further (调查diào chá to investigate/to survey/investigation/survey 提高tí gāo to improve/improvement 发展fā zhǎn to develop/development 扩大kuò dà to expand/expansion 研究yán jiū to research/research 指示zhǐ shì to instruct (from a superior)/ instruction (from a superior) 恶化è huà to deteriorate/deterioration 了解liǎo jiě to know well 改善gǎi shàn to ameliorate/amelioration 促进cù jìn to promote/promotion 加强jiā qiáng to strengthen 完善wán shàn to perfect/perfection 推进tuī jìn to carry forward 讨论tǎo lùn to discuss/discussion 分析fēn xī to analyze/analysis 说明shuō míng to illustrate/illustration)",
    page: 49,
    key: 117,
  },
  {
    pinyin: "zhī",
    chinese: "支",
    meaning:
      "measure word for long thin inflexible objects like 笔bǐ pen 香烟xiāng yān cigarette 箭jiàn arrow",
    page: 49,
    key: 118,
  },
  {
    pinyin: "zhǎi",
    chinese: "窄",
    meaning: "narrow (refers to opposite of wide)",
    page: 49,
    key: 119,
  },
  {
    pinyin: "àn qī",
    chinese: "按期",
    meaning: "on schedule (refers to on a specific date)",
    page: 49,
    key: 120,
  },
  {
    pinyin: "sù zhì",
    chinese: "素质",
    meaning: "quality (of a person)",
    page: 49,
    key: 121,
  },
  {
    pinyin: "fù èrdài",
    chinese: "富二代",
    meaning: "rich second generation",
    page: 49,
    key: 122,
  },
  {
    pinyin: "dào lù",
    chinese: "道路",
    meaning: "Road (more formal than 路lù)",
    page: 49,
    key: 123,
  },
  {
    pinyin: "lù biāo",
    chinese: "路标",
    meaning: "road sign",
    page: 49,
    key: 124,
  },
  {
    pinyin: "lù duàn",
    chinese: "路段",
    meaning: "section (of a road)",
    page: 49,
    key: 125,
  },
  {
    pinyin: "dì diǎn",
    chinese: "地点",
    meaning: "Site (more formal than 地方dì fang)",
    page: 49,
    key: 126,
  },
  {
    pinyin: "shàng jí",
    chinese: "上级",
    meaning: "superior (refers to somebody in a higher rank)",
    page: 49,
    key: 127,
  },
  {
    pinyin: "lín shí",
    chinese: "临时",
    meaning: "temporary/temporarily (refers to being improvised)",
    page: 49,
    key: 128,
  },
  {
    pinyin: "qún zhòng",
    chinese: "群众",
    meaning: "the masses",
    page: 49,
    key: 129,
  },
  {
    pinyin: "wú nài",
    chinese: "无奈",
    meaning: "To be helpless (about something) (formal)",
    page: 49,
    key: 130,
  },
  {
    pinyin: "jìn xíng",
    chinese: "进行",
    meaning:
      "To carry out (手术shǒu shù (surgical) operation 会议huì yì conference/meeting (of a group of people for work) 调查diào chá survey/investigation 实验shí yàn (scientific) experiment 比赛bǐ sài match 谈话tán huà conversation 统计tǒng jì to count up 交易jiāo yì (business) transaction 研究yán jiū research 观察guān chá observation 检查jiǎn chá inspection 交流jiāo liú communication 整顿zhěng dùn rectification 干预gàn yù intervention 考试kǎo shì (school) test) (more formal than 做zuò)",
    page: 49,
    key: 131,
  },
  {
    pinyin: "shī gōng",
    chinese: "施工",
    meaning: "to carry out construction",
    page: 49,
    key: 132,
  },
  {
    pinyin: "wán gōng",
    chinese: "完工",
    meaning: "to complete (a project)",
    page: 49,
    key: 133,
  },
  {
    pinyin: "jìn zhǐ",
    chinese: "禁止",
    meaning: "to forbid",
    page: 49,
    key: 134,
  },
  {
    pinyin: "jiāo gōng",
    chinese: "交工",
    meaning: "to hand over (a completed project)",
    page: 49,
    key: 135,
  },
  {
    pinyin: "dǎ liàng",
    chinese: "打量",
    meaning: "to look somebody up and down (for their appearance)",
    page: 49,
    key: 136,
  },
  {
    pinyin: "tōng zhī",
    chinese: "通知",
    meaning: "to notify/notice (refers to notification)",
    page: 49,
    key: 137,
  },
  {
    pinyin: "tōng xíng",
    chinese: "通行",
    meaning:
      "To pass through (a road, a door, a checkpoint etc) (more formal than 通过tōng guò)",
    page: 49,
    key: 138,
  },
  {
    pinyin: "yǒu dài",
    chinese: "有待",
    meaning:
      "To remain to be (解决jiě jué to settle or fix (a problem, issue, legal dispute and so on) 证明zhèng míng to prove 研究yán jiū to research 提高tí gāo to improve 讨论tǎo lùn to discuss 确定què dìng to ascertain or decide on 改进gǎi jìn to improve 调查diào chá to investigate/to survey 开发kāi fā to develop 确认què rèn to confirm 验证yàn zhèng to verify (by a test or experiment) 回答huí dá to answer (a question) 考证kǎo zhèng to verify (by investigation) 决定jué dìng to decide 完成wán chéng to complete 观察guān chá to observe 实现shí xiàn to realize 实践shí jiàn to put into practice 挖掘wā jué to excavate 鉴定jiàn dìng to appraise or authenticate (an object) 推广tuī guǎng to popularize 探索tàn suǒ to explore (scientifically) 完善wán shàn to perfect 提升tí shēng to promote 加强jiā qiáng to strengthen 改善gǎi shàn to ameliorate) (formal)",
    page: 49,
    key: 139,
  },
  {
    pinyin: "qiān dào",
    chinese: "签到",
    meaning: "to sign in",
    page: 49,
    key: 140,
  },
  {
    pinyin: "kāi gōng",
    chinese: "开工",
    meaning: "to start operation (in a factory)/to start construction",
    page: 49,
    key: 141,
  },
  {
    pinyin: "chéng",
    chinese: "乘",
    meaning: "to take (a transportation)",
    page: 49,
    key: 142,
  },
  {
    pinyin: "dā",
    chinese: "搭",
    meaning: "to take (a transportation) (informal)",
    page: 49,
    key: 143,
  },
  {
    pinyin: "chéng zuò",
    chinese: "乘坐",
    meaning: "To take (a transportation) (more formal than 乘chéng)",
    page: 49,
    key: 144,
  },
  {
    pinyin: "shōu gōng",
    chinese: "收工",
    meaning: "to wrap up (a job)",
    page: 49,
    key: 145,
  },
  {
    pinyin: "kuān",
    chinese: "宽",
    meaning: "wide",
    page: 49,
    key: 146,
  },
  {
    pinyin: "wúxiàn wǎng",
    chinese: "无线网",
    meaning: "wifi",
    page: 49,
    key: 147,
  },
  {
    pinyin: "guī ju",
    chinese: "规矩",
    meaning: "(customary) rule",
    page: 50,
    key: 148,
  },
  {
    pinyin: "liáng kuài",
    chinese: "凉快",
    meaning: "(pleasantly) cool (refers to air temperature)",
    page: 50,
    key: 149,
  },
  {
    pinyin: "yòng gōng",
    chinese: "用功",
    meaning: "(to study) hard",
    page: 50,
    key: 150,
  },
  {
    pinyin: "lóng zi",
    chinese: "聋子",
    meaning: "a deaf person",
    page: 50,
    key: 151,
  },
  {
    pinyin: "běn shì",
    chinese: "本事",
    meaning: "ability (informal)",
    page: 50,
    key: 152,
  },
  {
    pinyin: "quán",
    chinese: "全",
    meaning:
      "All (more formal than 都dōu)/whole or complete (refers to include all the parts)",
    page: 50,
    key: 153,
  },
  {
    pinyin: "tǎo yàn",
    chinese: "讨厌",
    meaning: "annoying/to dislike",
    page: 50,
    key: 154,
  },
  {
    pinyin: "xiā",
    chinese: "瞎",
    meaning: "blind",
    page: 50,
    key: 155,
  },
  {
    pinyin: "zhōng yāng",
    chinese: "中央",
    meaning:
      "center (of a place or something not bigger than a public square)/central authorities (of a country or political party)",
    page: 50,
    key: 156,
  },
  {
    pinyin: "tiáo jiàn",
    chinese: "条件",
    meaning: "conditions/terms (of an agreement)",
    page: 50,
    key: 157,
  },
  {
    pinyin: "jìng sài",
    chinese: "竞赛",
    meaning: "contest",
    page: 50,
    key: 158,
  },
  {
    pinyin: "liáng",
    chinese: "凉",
    meaning: "cool (refers to temperature)",
    page: 50,
    key: 159,
  },
  {
    pinyin: "jiǎo luò",
    chinese: "角落",
    meaning: "corner (of a place)",
    page: 50,
    key: 160,
  },
  {
    pinyin: "xié duìmiàn",
    chinese: "斜对面",
    meaning: "diagonally opposite",
    page: 50,
    key: 161,
  },
  {
    pinyin: "chán",
    chinese: "馋",
    meaning: "greedy (for food)",
    page: 50,
    key: 162,
  },
  {
    pinyin: "huó gāi",
    chinese: "活该",
    meaning: "it serves somebody right",
    page: 50,
    key: 163,
  },
  {
    pinyin: "gài zi",
    chinese: "盖子",
    meaning: "lid (of a container)",
    page: 50,
    key: 164,
  },
  {
    pinyin: "dà tīng",
    chinese: "大厅",
    meaning: "lobby (of a building)/hall",
    page: 50,
    key: 165,
  },
  {
    pinyin: "xiǎo tuǐ",
    chinese: "小腿",
    meaning: "lower leg",
    page: 50,
    key: 166,
  },
  {
    pinyin: "qiān xū",
    chinese: "谦虚",
    meaning: "modest (of a person)",
    page: 50,
    key: 167,
  },
  {
    pinyin: "guò shí",
    chinese: "过时",
    meaning: "outdated",
    page: 50,
    key: 168,
  },
  {
    pinyin: "guò fèn",
    chinese: "过分",
    meaning:
      "over- (强调qiáng diào to emphasize 要求yāo qiú to demand/demand 谦虚qiān xū modest 敏感mǐn gǎn sensitive 讲究jiǎng jiū to be particular about 依赖yī lài to rely on 相信xiāng xìn to believe 集中jí zhōng to concentrate 自信zì xìn to be self-confident 紧张jǐn zhāng to be nervous 追求zhuī qiú to pursue)",
    page: 50,
    key: 169,
  },
  {
    pinyin: "míng cì",
    chinese: "名次",
    meaning: "position (in a competition)",
    page: 50,
    key: 170,
  },
  {
    pinyin: "mán",
    chinese: "蛮",
    meaning: "quite (less formal than 挺tǐng)",
    page: 50,
    key: 171,
  },
  {
    pinyin: "jiǎngxué jīn",
    chinese: "奖学金",
    meaning: "scholarship (refers to money)",
    page: 50,
    key: 172,
  },
  {
    pinyin: "xié",
    chinese: "斜",
    meaning: "slanting",
    page: 50,
    key: 173,
  },
  {
    pinyin: "shú rén/shóu rén",
    chinese: "熟人",
    meaning: "somebody who one has already known each other",
    page: 50,
    key: 174,
  },
  {
    pinyin: "quán xiào",
    chinese: "全校",
    meaning: "the whole school",
    page: 50,
    key: 175,
  },
  {
    pinyin: "dà tuǐ",
    chinese: "大腿",
    meaning: "thigh",
    page: 50,
    key: 176,
  },
  {
    pinyin: "chī cù",
    chinese: "吃醋",
    meaning: "to be jealous (of romantic love)",
    page: 50,
    key: 177,
  },
  {
    pinyin: "shě bùdé",
    chinese: "舍不得",
    meaning: "to be not willing to (give up something)",
    page: 50,
    key: 178,
  },
  {
    pinyin: "jiāo ào",
    chinese: "骄傲",
    meaning: "to be proud",
    page: 50,
    key: 179,
  },
  {
    pinyin: "gài",
    chinese: "盖",
    meaning: "to cover (over surface)/to build (a house)",
    page: 50,
    key: 180,
  },
  {
    pinyin: "chā duì",
    chinese: "插队",
    meaning: "to cut in line/to jump a queue",
    page: 50,
    key: 181,
  },
  {
    pinyin: "lín shī",
    chinese: "淋湿",
    meaning: "to get soaked",
    page: 50,
    key: 182,
  },
  {
    pinyin: "chū guó",
    chinese: "出国",
    meaning: "to go abroad",
    page: 50,
    key: 183,
  },
  {
    pinyin: "dù jīn",
    chinese: "镀金",
    meaning:
      "to go somewhere (usually abroad) to study in order to enhance one's social status (original meaning: to get gilded)",
    page: 50,
    key: 184,
  },
  {
    pinyin: "chī kǔ",
    chinese: "吃苦",
    meaning: "to have a rough time/to work hard",
    page: 50,
    key: 185,
  },
  {
    pinyin: "chā",
    chinese: "插",
    meaning: "to insert",
    page: 50,
    key: 186,
  },
  {
    pinyin: "qiáo",
    chinese: "瞧",
    meaning: "to look (at) (informal)",
    page: 50,
    key: 187,
  },
  {
    pinyin: "nào xiàohuà",
    chinese: "闹笑话",
    meaning: "to make a fool of oneself",
    page: 50,
    key: 188,
  },
  {
    pinyin: "dài kuǎn",
    chinese: "贷款",
    meaning:
      "to provide or to ask for a loan (from an organization, usually a bank)/loan",
    page: 50,
    key: 189,
  },
  {
    pinyin: "jiàn wài",
    chinese: "见外",
    meaning: "to regard somebody as an outsider (refers to being too polite)",
    page: 50,
    key: 190,
  },
  {
    pinyin: "zhuàn",
    chinese: "转",
    meaning: "to revolve",
    page: 50,
    key: 191,
  },
  {
    pinyin: "sàn bù",
    chinese: "散步",
    meaning: "to take a walk",
    page: 50,
    key: 192,
  },
  {
    pinyin: "bǎo bèi",
    chinese: "宝贝",
    meaning: "treasured object/darling",
    page: 50,
    key: 193,
  },
  {
    pinyin: "guāi",
    chinese: "乖",
    meaning: "well-behaved (of a child)",
    page: 50,
    key: 194,
  },
  {
    pinyin: "shī",
    chinese: "湿",
    meaning: "wet",
    page: 50,
    key: 195,
  },
  {
    pinyin: "láng",
    chinese: "狼",
    meaning: "wolf",
    page: 50,
    key: 196,
  },
  {
    pinyin: "sè láng",
    chinese: "色狼",
    meaning:
      "wolf (refers to a man who is aggressive in making sexual advances to women)",
    page: 50,
    key: 197,
  },
  {
    pinyin: "xìng gé",
    chinese: "性格",
    meaning: "(a person's general) personality",
    page: 51,
    key: 198,
  },
  {
    pinyin: "zhǐ jīn",
    chinese: "纸巾",
    meaning: "tissue paper",
    page: 51,
    key: 199,
  },
  {
    pinyin: "míng tang",
    chinese: "名堂",
    meaning: "(interesting) stuff (informal)",
    page: 51,
    key: 200,
  },
  {
    pinyin: "shuǎng",
    chinese: "爽",
    meaning: "(to feel) fantastic",
    page: 51,
    key: 201,
  },
  {
    pinyin: "chèn zǎo",
    chinese: "趁早",
    meaning: "before it's too late",
    page: 51,
    key: 202,
  },
  {
    pinyin: "jiào yǎng",
    chinese: "教养",
    meaning: "breeding (of a person)",
    page: 51,
    key: 203,
  },
  {
    pinyin: "xiōng dì",
    chinese: "兄弟",
    meaning: "brothers/buddy",
    page: 51,
    key: 204,
  },
  {
    pinyin: "gē men",
    chinese: "哥们",
    meaning: "buddy",
    page: 51,
    key: 205,
  },
  {
    pinyin: "fēng dù",
    chinese: "风度",
    meaning: "demeanor",
    page: 51,
    key: 206,
  },
  {
    pinyin: "bié kàn",
    chinese: "别看",
    meaning: "don't judge from",
    page: 51,
    key: 207,
  },
  {
    pinyin: "bǐ cǐ",
    chinese: "彼此",
    meaning: "Each other (formal)",
    page: 51,
    key: 208,
  },
  {
    pinyin: "dòng búdòng",
    chinese: "动不动",
    meaning: "easily (happens something bad)",
    page: 51,
    key: 209,
  },
  {
    pinyin: "chǎng zhǎng",
    chinese: "厂长",
    meaning: "factory director",
    page: 51,
    key: 210,
  },
  {
    pinyin: "xiǎo zi",
    chinese: "小子",
    meaning: "fellow (an informal way to mean a man or boy)",
    page: 51,
    key: 211,
  },
  {
    pinyin: "tā māde",
    chinese: "他妈的",
    meaning: "fucking",
    page: 51,
    key: 212,
  },
  {
    pinyin: "shēn shì",
    chinese: "绅士",
    meaning: "gentleman (outdated)",
    page: 51,
    key: 213,
  },
  {
    pinyin: "zhēn zhèng",
    chinese: "真正",
    meaning:
      "Genuine (refers to real) (more formal than 真的zhēn de) (attribute)/Genuinely (refers to really) (more formal than 真的zhēn de)",
    page: 51,
    key: 214,
  },
  {
    pinyin: "xiàng qīn",
    chinese: "相亲",
    meaning: "matchmaking date",
    page: 51,
    key: 215,
  },
  {
    pinyin: "bú xiànghuà",
    chinese: "不像话",
    meaning: "outrageous (of behaviour) (informal)",
    page: 51,
    key: 216,
  },
  {
    pinyin: "kē zhǎng",
    chinese: "科长",
    meaning: "section chief",
    page: 51,
    key: 217,
  },
  {
    pinyin: "yì yì",
    chinese: "意义",
    meaning: "significance",
    page: 51,
    key: 218,
  },
  {
    pinyin: "jiě mèi",
    chinese: "姐妹",
    meaning: "sisters/bestie",
    page: 51,
    key: 219,
  },
  {
    pinyin: "tè shū",
    chinese: "特殊",
    meaning: "Special (more formal than 特别tè bié)",
    page: 51,
    key: 220,
  },
  {
    pinyin: "èr",
    chinese: "二",
    meaning: "stupid (of a person) (informal)",
    page: 51,
    key: 221,
  },
  {
    pinyin: "huī xīn",
    chinese: "灰心",
    meaning: "to be discouraged",
    page: 51,
    key: 222,
  },
  {
    pinyin: "zhuī",
    chinese: "追",
    meaning: "to chase after",
    page: 51,
    key: 223,
  },
  {
    pinyin: "hài/hài de",
    chinese: "害/害得",
    meaning: "to do or cause (harm or trouble to) (informal)",
    page: 51,
    key: 224,
  },
  {
    pinyin: "gǔn/gǔn kāi/gǔn dàn",
    chinese: "滚/滚开/滚蛋",
    meaning: "to fuck off",
    page: 51,
    key: 225,
  },
  {
    pinyin: "sòng lǐ",
    chinese: "送礼",
    meaning: "to give a present",
    page: 51,
    key: 226,
  },
  {
    pinyin: "shàng chuáng",
    chinese: "上床",
    meaning: "to go to bed/to have sex with somebody (euphemism)",
    page: 51,
    key: 227,
  },
  {
    pinyin: "pāi mǎpì",
    chinese: "拍马屁",
    meaning: "to kiss ass",
    page: 51,
    key: 228,
  },
  {
    pinyin: "pèi",
    chinese: "配",
    meaning: "to match",
    page: 51,
    key: 229,
  },
  {
    pinyin: "dā pèi",
    chinese: "搭配",
    meaning:
      "to match up (词语cí yǔ word 颜色yán sè colour 衣服yī fu clothes 家具jiā jù furniture 食物shí wù food)",
    page: 51,
    key: 230,
  },
  {
    pinyin: "xián",
    chinese: "嫌",
    meaning: "to not like (some aspect of something or somebody)",
    page: 51,
    key: 231,
  },
  {
    pinyin: "kuā",
    chinese: "夸",
    meaning: "to praise",
    page: 51,
    key: 232,
  },
  {
    pinyin: "zá",
    chinese: "砸",
    meaning: "to smash",
    page: 51,
    key: 233,
  },
  {
    pinyin: "wàn wàn",
    chinese: "万万",
    meaning:
      "used to strengthen the negative tone (followed by 不bù/bú or 没/没有méi/méi yǒu either to warn or remind somebody not to do something or impossible to happen something)",
    page: 51,
    key: 234,
  },
  {
    pinyin: "fù",
    chinese: "副",
    meaning:
      "vice- (总统zǒng tǒng president (of a country) 经理jīng lǐ manager 主席zhǔ xí chairman 厂长chǎng zhǎng factory director 书记shū jì secretary 校长xiào zhǎng principal (of a school))",
    page: 51,
    key: 235,
  },
  {
    pinyin: "tiān xià",
    chinese: "天下",
    meaning: "world (outdated)",
    page: 51,
    key: 236,
  },
  {
    pinyin: "yí dìng",
    chinese: "一定",
    meaning: "a certain (amount or extent) (attribute)",
    page: 52,
    key: 237,
  },
  {
    pinyin: "kǒu yīn",
    chinese: "口音",
    meaning: "(local) accent",
    page: 52,
    key: 238,
  },
  {
    pinyin: "xīn kǔ",
    chinese: "辛苦",
    meaning: "(to labor or work) hard",
    page: 52,
    key: 239,
  },
  {
    pinyin: "fǎn cháng",
    chinese: "反常",
    meaning: "abnormal",
    page: 52,
    key: 240,
  },
  {
    pinyin: "liǎo buqǐ",
    chinese: "了不起",
    meaning: "great (with ability or achievement)",
    page: 52,
    key: 241,
  },
  {
    pinyin: "xìng huì",
    chinese: "幸会",
    meaning: "honoured to meet you (used for greeting)",
    page: 52,
    key: 242,
  },
  {
    pinyin: "zǎ",
    chinese: "咋",
    meaning: "how/how come (more informal than 怎么zěn me)",
    page: 52,
    key: 243,
  },
  {
    pinyin: "má jiàng",
    chinese: "麻将",
    meaning: "mahjong",
    page: 52,
    key: 244,
  },
  {
    pinyin: "zuǐ yìng",
    chinese: "嘴硬",
    meaning: "not admit oneself wrong (literally: mouth hard)",
    page: 52,
    key: 245,
  },
  {
    pinyin: "fèi huà",
    chinese: "废话",
    meaning: "one's words which are completely useless",
    page: 52,
    key: 246,
  },
  {
    pinyin: "kǒu yǔ",
    chinese: "口语",
    meaning: "spoken language",
    page: 52,
    key: 247,
  },
  {
    pinyin: "chè dǐ",
    chinese: "彻底",
    meaning: "thorough (refers to thoroughgoing)/thoroughly",
    page: 52,
    key: 248,
  },
  {
    pinyin: "róng xìng",
    chinese: "荣幸",
    meaning: "to be honored",
    page: 52,
    key: 249,
  },
  {
    pinyin: "dé yì",
    chinese: "得意",
    meaning: "to be smug",
    page: 52,
    key: 250,
  },
  {
    pinyin: "xīn fán",
    chinese: "心烦",
    meaning: "to be upset",
    page: 52,
    key: 251,
  },
  {
    pinyin: "jiě mèn",
    chinese: "解闷",
    meaning: "to divert oneself (from boredom)",
    page: 52,
    key: 252,
  },
  {
    pinyin: "tǐ yàn",
    chinese: "体验",
    meaning: "to experience (for a try)/experience (from a try)",
    page: 52,
    key: 253,
  },
  {
    pinyin: "liàng",
    chinese: "晾",
    meaning: "to hang (for drying)",
    page: 52,
    key: 254,
  },
  {
    pinyin: "xiǎo de",
    chinese: "晓得",
    meaning: "to know (facts or information) (more informal than 知道zhī dào)",
    page: 52,
    key: 255,
  },
  {
    pinyin: "fā cái",
    chinese: "发财",
    meaning: "to make a fortune",
    page: 52,
    key: 256,
  },
  {
    pinyin: "cún xīn",
    chinese: "存心",
    meaning: "to mean to (do something bad to others)",
    page: 52,
    key: 257,
  },
  {
    pinyin: "lāo dao",
    chinese: "唠叨",
    meaning: "to nag",
    page: 52,
    key: 258,
  },
  {
    pinyin: "zhàn",
    chinese: "占",
    meaning: "to occupy",
    page: 52,
    key: 259,
  },
  {
    pinyin: "jiè yān",
    chinese: "戒烟",
    meaning: "to quit smoking",
    page: 52,
    key: 260,
  },
  {
    pinyin: "chéng shòu",
    chinese: "承受",
    meaning:
      "to sustain (痛苦tòng kǔ pain 重量zhòng liàng weight 压力yā lì pressure 考验kǎo yàn test 损失sǔn shī loss 打击dǎ jī (emotional) blow)",
    page: 52,
    key: 261,
  },
  {
    pinyin: "xī han",
    chinese: "稀罕",
    meaning: "to value as a rarity (informal)",
    page: 52,
    key: 262,
  },
  {
    pinyin: "shá",
    chinese: "啥",
    meaning: "what (more informal than 什么shén me)",
    page: 52,
    key: 263,
  },
  {
    pinyin: "mào yì",
    chinese: "贸易",
    meaning: "(commercial exchanging) trade",
    page: 53,
    key: 264,
  },
  {
    pinyin: "dài lǐ",
    chinese: "代理",
    meaning:
      "an agent or agency who acts on behalf of somebody for their business interests/to act as an agent or agency",
    page: 53,
    key: 265,
  },
  {
    pinyin: "lì kè/lì jí",
    chinese: "立刻/立即",
    meaning: "At once (refers to immediately) (more formal than 马上mǎ shàng)",
    page: 53,
    key: 266,
  },
  {
    pinyin: "fēn diàn",
    chinese: "分店",
    meaning: "branch (of a shop)",
    page: 53,
    key: 267,
  },
  {
    pinyin: "fēn gōngsī",
    chinese: "分公司",
    meaning: "branch office",
    page: 53,
    key: 268,
  },
  {
    pinyin: "mǒu",
    chinese: "某",
    meaning: "certain (refers to particular but not specified)",
    page: 53,
    key: 269,
  },
  {
    pinyin: "gǔ wén",
    chinese: "古文",
    meaning: "classical Chinese",
    page: 53,
    key: 270,
  },
  {
    pinyin: "míng pái",
    chinese: "名牌",
    meaning: "famous brand",
    page: 53,
    key: 271,
  },
  {
    pinyin: "shìwù suǒ",
    chinese: "事务所",
    meaning:
      "firm (usually refers to 律师事务所lǜshī shìwù suǒ law firm or 会计事务所kuàijì shìwù suǒ accounting firm)",
    page: 53,
    key: 272,
  },
  {
    pinyin: "wài qǐ",
    chinese: "外企",
    meaning: "foreign enterprise",
    page: 53,
    key: 273,
  },
  {
    pinyin: "niú bī",
    chinese: "牛B",
    meaning: "great (with ability or achievement) (informal)",
    page: 53,
    key: 274,
  },
  {
    pinyin: "lǜ kǎ",
    chinese: "绿卡",
    meaning: "green card",
    page: 53,
    key: 275,
  },
  {
    pinyin: "zǒng bù",
    chinese: "总部",
    meaning: "headquarter",
    page: 53,
    key: 276,
  },
  {
    pinyin: "gāo děng",
    chinese: "高等",
    meaning:
      "higher (动物dòng wù animal 学校xué xiào school 教育jiāo yù education 数学shù xué maths) (attribute)",
    page: 53,
    key: 277,
  },
  {
    pinyin: "gāo jí",
    chinese: "高级",
    meaning:
      "high-level (官员guān yuán government official 汉语hàn yǔ Mandarin 酒店jiǔ diàn hotel 工程师gōngchéng shī engineer 搜索sōu suǒ search 中学zhōng xué middle school 法院fǎ yuàn (law) court 旅馆lǚ guǎn hotel 人才rén cái talented person) (attribute)",
    page: 53,
    key: 278,
  },
  {
    pinyin: "wén máng",
    chinese: "文盲",
    meaning: "illiterate person",
    page: 53,
    key: 279,
  },
  {
    pinyin: "gè dì",
    chinese: "各地",
    meaning: "in all parts (of the world or a country)",
    page: 53,
    key: 280,
  },
  {
    pinyin: "guān jiàn",
    chinese: "关键",
    meaning: "key (refers to crucial or crucial point)",
    page: 53,
    key: 281,
  },
  {
    pinyin: "huí kòu",
    chinese: "回扣",
    meaning: "kickback",
    page: 53,
    key: 282,
  },
  {
    pinyin: "chǎng shāng",
    chinese: "厂商",
    meaning: "manufacturer",
    page: 53,
    key: 283,
  },
  {
    pinyin: "yī yào",
    chinese: "医药",
    meaning:
      "medicine or pharmacy (行业háng yè industry 专家zhuān jiā specialist/expert 公司gōng sī company 费fèi fee 箱xiāng box 网站wǎng zhàn website 杂志zá zhì magazine 电商diàn shāng electric commercial enterprise 企业qǐ yè enterprise 安全ān quán safety) (attribute)",
    page: 53,
    key: 284,
  },
  {
    pinyin: "sī yíng",
    chinese: "私营",
    meaning:
      "privately run (公司gōng sī company 企业qǐ yè enterprise 商店shāng diàn shop 机构jī gòu institution 银行yín háng bank 医院yī yuàn hospital 经济jīng jì economy)",
    page: 53,
    key: 285,
  },
  {
    pinyin: "xiāng dāng",
    chinese: "相当",
    meaning: "Quite (more formal than 挺tǐng)",
    page: 53,
    key: 286,
  },
  {
    pinyin: "xiāo liàng/xiāoshòu liàng",
    chinese: "销量/销售量",
    meaning: "sales volume/quantity of sales",
    page: 53,
    key: 287,
  },
  {
    pinyin: "shí zì",
    chinese: "识字",
    meaning: "to be able to read",
    page: 53,
    key: 288,
  },
  {
    pinyin: "guān zhào",
    chinese: "关照",
    meaning:
      "to be concerned and look after (short for 关心guān xīn and 照顾zhào gù)",
    page: 53,
    key: 289,
  },
  {
    pinyin: "jiāo huàn",
    chinese: "交换",
    meaning: "To exchange (with each other) (more formal than 换huàn)",
    page: 53,
    key: 290,
  },
  {
    pinyin: "kuò dà",
    chinese: "扩大",
    meaning:
      "to expand (范围fàn wéi scope or limits (of something) 合作hé zuò cooperation 业务yè wù affair (of business) 影响yǐng xiǎng influence 生产shēng chǎn production 市场shì chǎng market 内需nèi xū domestic demand 优势yōu shì advantage (over the other party))/expansion",
    page: 53,
    key: 291,
  },
  {
    pinyin: "bì yè",
    chinese: "毕业",
    meaning: "to graduate/(school) graduation",
    page: 53,
    key: 292,
  },
  {
    pinyin: "gāo jiù",
    chinese: "高就",
    meaning: "To have a job (more polite than 工作gōng zuò)",
    page: 53,
    key: 293,
  },
  {
    pinyin: "shī qù",
    chinese: "失去",
    meaning:
      "to lose (控制kòng zhì control 信心xìn xīn confidence 兴趣xìng qù interest 知觉zhī jué consciousness 联系lián xì contact 平衡píng héng balance 意识yì shí awareness 生命shēng mìng life 机会jī huì chance 资格zī gé qualification)",
    page: 53,
    key: 294,
  },
  {
    pinyin: "bàn zhèng",
    chinese: "办证",
    meaning: "to make credential",
    page: 53,
    key: 295,
  },
  {
    pinyin: "líng shòu",
    chinese: "零售",
    meaning: "to retail",
    page: 53,
    key: 296,
  },
  {
    pinyin: "xiāo shòu",
    chinese: "销售",
    meaning:
      "To sell (more formal than 卖mài)/sale (refers to the activity of selling)",
    page: 53,
    key: 297,
  },
  {
    pinyin: "dūn",
    chinese: "蹲",
    meaning: "to squat (on the heels)",
    page: 53,
    key: 298,
  },
  {
    pinyin: "tí chéng",
    chinese: "提成",
    meaning: "to take a percentage commission/(percentage) commission",
    page: 53,
    key: 299,
  },
  {
    pinyin: "cǐ wài",
    chinese: "此外",
    meaning: "What's more (more formal than 另外lìng wài)",
    page: 53,
    key: 300,
  },
  {
    pinyin: "pī fā",
    chinese: "批发",
    meaning: "wholesale",
    page: 53,
    key: 301,
  },
  {
    pinyin: "xiǎng",
    chinese: "响",
    meaning: "to ring (of a phone, alarm clock, or bell, etc)/to make a sound",
    page: 54,
    key: 302,
  },
  {
    pinyin: "yǎn chū",
    chinese: "演出",
    meaning: "(stage) performance",
    page: 54,
    key: 303,
  },
  {
    pinyin: "xí sú",
    chinese: "习俗",
    meaning: "(traditional, local or country's) custom",
    page: 54,
    key: 304,
  },
  {
    pinyin: "wèi kǒu",
    chinese: "胃口",
    meaning: "appetite (for food)",
    page: 54,
    key: 305,
  },
  {
    pinyin: "guān zhòng",
    chinese: "观众",
    meaning: "audience (refers to spectator)",
    page: 54,
    key: 306,
  },
  {
    pinyin: "kuài zi",
    chinese: "筷子",
    meaning: "chopstick",
    page: 54,
    key: 307,
  },
  {
    pinyin: "zhèng jiàn",
    chinese: "证件",
    meaning: "credential",
    page: 54,
    key: 308,
  },
  {
    pinyin: "rén qún",
    chinese: "人群",
    meaning: "crowd",
    page: 54,
    key: 309,
  },
  {
    pinyin: "tóng zhuō",
    chinese: "同桌",
    meaning: "deskmate",
    page: 54,
    key: 310,
  },
  {
    pinyin: "gè wèi",
    chinese: "各位",
    meaning: "Everybody (used to address to a group of people) (formal)",
    page: 54,
    key: 311,
  },
  {
    pinyin: "shǎo bùliǎo",
    chinese: "少不了",
    meaning: "indispensable/cannot be avoided",
    page: 54,
    key: 312,
  },
  {
    pinyin: "bǎo xiǎn",
    chinese: "保险",
    meaning: "insurance/safe (opposite of risky)",
    page: 54,
    key: 313,
  },
  {
    pinyin: "dāng dì",
    chinese: "当地",
    meaning: "local (refers to that area)",
    page: 54,
    key: 314,
  },
  {
    pinyin: "xìng zhì",
    chinese: "兴致",
    meaning: "mood (for enjoyment)",
    page: 54,
    key: 315,
  },
  {
    pinyin: "dòng fáng",
    chinese: "洞房",
    meaning:
      "nuptial chamber/to perform the duties of marriage on the wedding night",
    page: 54,
    key: 316,
  },
  {
    pinyin: "qí",
    chinese: "齐",
    meaning: "on the same plane with/not lack of any",
    page: 54,
    key: 317,
  },
  {
    pinyin: "yánjiū shēng",
    chinese: "研究生",
    meaning: "postgraduate student",
    page: 54,
    key: 318,
  },
  {
    pinyin: "gōng zī",
    chinese: "工资",
    meaning: "salary",
    page: 54,
    key: 319,
  },
  {
    pinyin: "shè jiāo",
    chinese: "社交",
    meaning:
      "social (场合chǎng hé occasion 生活shēng huó life 礼节lǐ jié courtesy 软件ruǎn jiàn software 平台píng tái platform 技巧jì qiǎo technique 信息xìn xī information 媒体méi tǐ media 网站wǎng zhàn website 能力néng lì ability 活动huó dòng event 礼仪lǐ yí etiquette 恐惧症kǒngjù zhèng phobia) (attribute)",
    page: 54,
    key: 320,
  },
  {
    pinyin: "yìng chou",
    chinese: "应酬",
    meaning: "social engagement (like a dinner or party because of work)",
    page: 54,
    key: 321,
  },
  {
    pinyin: "jīng cǎi",
    chinese: "精彩",
    meaning:
      "splendid (表演biǎo yǎn (entertaining) performance 故事gù shì story 演出yǎn chū (stage) performance 演讲yǎn jiǎng speech 电影diàn yǐng movie 比赛bǐ sài match 节目jié mù (TV, radio) programme 发言fā yán speech 游戏yóu xì (recreational) game 人生rén shēng life 小说xiǎo shuō novel/fiction)",
    page: 54,
    key: 322,
  },
  {
    pinyin: "wèi",
    chinese: "胃",
    meaning: "stomach (where food is digested)",
    page: 54,
    key: 323,
  },
  {
    pinyin: "duì xiàng",
    chinese: "对象",
    meaning:
      "target or object (which is focused on)/partner (somebody's getting married to)",
    page: 54,
    key: 324,
  },
  {
    pinyin: "dà zhòng",
    chinese: "大众",
    meaning: "the masses",
    page: 54,
    key: 325,
  },
  {
    pinyin: "shú xī/shóu xī",
    chinese: "熟悉",
    meaning: "To be familiar with (more formal than 熟shú)",
    page: 54,
    key: 326,
  },
  {
    pinyin: "zài zuò",
    chinese: "在座",
    meaning: "to be present sitting (at a meeting, gathering, conference etc)",
    page: 54,
    key: 327,
  },
  {
    pinyin: "chī jīng",
    chinese: "吃惊",
    meaning: "to be surprised",
    page: 54,
    key: 328,
  },
  {
    pinyin: "pāi shǒu",
    chinese: "拍手",
    meaning: "to clap one's hands",
    page: 54,
    key: 329,
  },
  {
    pinyin: "jiá",
    chinese: "夹",
    meaning: "to clip (refers to press from both sides)",
    page: 54,
    key: 330,
  },
  {
    pinyin: "suí",
    chinese: "随",
    meaning: "To follow (someone or something moving) (more formal than 跟gēn)",
    page: 54,
    key: 331,
  },
  {
    pinyin: "hù dòng",
    chinese: "互动",
    meaning: "to interact (with at least one person)/interactive",
    page: 54,
    key: 332,
  },
  {
    pinyin: "liú xīn/liú yì",
    chinese: "留心/留意",
    meaning: "to keep an eye on/to keep in mind",
    page: 54,
    key: 333,
  },
  {
    pinyin: "tāo",
    chinese: "掏",
    meaning: "to pull (out of a pocket)",
    page: 54,
    key: 334,
  },
  {
    pinyin: "yán jiū",
    chinese: "研究",
    meaning: "to research/research",
    page: 54,
    key: 335,
  },
  {
    pinyin: "dòng shǒu",
    chinese: "动手",
    meaning: "to start (to do some activity)/do-it-yourself",
    page: 54,
    key: 336,
  },
  {
    pinyin: "shēn",
    chinese: "伸",
    meaning: "to stretch",
    page: 54,
    key: 337,
  },
  {
    pinyin: "wéi",
    chinese: "围",
    meaning: "to surround",
    page: 54,
    key: 338,
  },
  {
    pinyin: "rì zi",
    chinese: "日子",
    meaning: "(particular) day",
    page: 55,
    key: 339,
  },
  {
    pinyin: "qiáng pò",
    chinese: "强迫",
    meaning:
      "(somebody) To force (somebody to do something) (more formal than 逼bī)",
    page: 55,
    key: 340,
  },
  {
    pinyin: "gē bo",
    chinese: "胳膊",
    meaning: "arm (of a body)",
    page: 55,
    key: 341,
  },
  {
    pinyin: "yǐ",
    chinese: "以",
    meaning: "By means of (more formal than 用yòng)",
    page: 55,
    key: 342,
  },
  {
    pinyin: "mò fēi",
    chinese: "莫非",
    meaning:
      "Don’t tell me (to express one's assumption) (more formal than 难道nán dào)",
    page: 55,
    key: 343,
  },
  {
    pinyin: "chū cì",
    chinese: "初次",
    meaning: "For the first time (more formal than 第一次dìyī cì)",
    page: 55,
    key: 344,
  },
  {
    pinyin: "lián xù",
    chinese: "连续",
    meaning:
      "In a row (refers to in succession) (more formal than 一连/连着yì lián/lián zhe)",
    page: 55,
    key: 345,
  },
  {
    pinyin: "lù xù",
    chinese: "陆续",
    meaning: "One after another (formal)",
    page: 55,
    key: 346,
  },
  {
    pinyin: "sī shì",
    chinese: "私事",
    meaning: "private matter",
    page: 55,
    key: 347,
  },
  {
    pinyin: "shí zài",
    chinese: "实在",
    meaning: "really (to emphasize an adjective or verb)/down to earth",
    page: 55,
    key: 348,
  },
  {
    pinyin: "zōng jiào",
    chinese: "宗教",
    meaning: "religion",
    page: 55,
    key: 349,
  },
  {
    pinyin: "chū xiàn",
    chinese: "出现",
    meaning:
      "to appear (refers to show up)/appearance (refers to event of coming into sight)",
    page: 55,
    key: 350,
  },
  {
    pinyin: "miǎn",
    chinese: "免",
    meaning: "to be exempt from",
    page: 55,
    key: 351,
  },
  {
    pinyin: "hài xiū",
    chinese: "害羞",
    meaning: "to be shy",
    page: 55,
    key: 352,
  },
  {
    pinyin: "jiāo dài",
    chinese: "交代",
    meaning:
      "to brief or to confess (工作gōng zuò work 事情shì qíng matter 任务rèn wù task 政策zhèng cè policy 罪行zuì xíng crime)",
    page: 55,
    key: 353,
  },
  {
    pinyin: "sàn",
    chinese: "散",
    meaning: "to disperse",
    page: 55,
    key: 354,
  },
  {
    pinyin: "wú guān",
    chinese: "无关",
    meaning:
      "To have nothing to do with (more formal than 没有关系méiyǒu guānxi)",
    page: 55,
    key: 355,
  },
  {
    pinyin: "chā shǒu",
    chinese: "插手",
    meaning: "to meddle",
    page: 55,
    key: 356,
  },
  {
    pinyin: "yǔn xǔ",
    chinese: "允许",
    meaning: "To permit (more formal than 准zhǔn)/permission",
    page: 55,
    key: 357,
  },
  {
    pinyin: "zhuài",
    chinese: "拽",
    meaning: "to tug",
    page: 55,
    key: 358,
  },
  {
    pinyin: "qíng yuàn",
    chinese: "情愿",
    meaning: "Would rather/To be willing to (formal)",
    page: 55,
    key: 359,
  },
  {
    pinyin: "méi zhǔn",
    chinese: "没准",
    meaning: "maybe (less formal than 说不定shuō bú dìng)",
    page: 42,
    key: 360,
  },
  {
    pinyin: "xíng hào",
    chinese: "型号",
    meaning: "model (of a product)",
    page: 42,
    key: 361,
  },
  {
    pinyin: "dà buliǎo",
    chinese: "大不了",
    meaning: "no worse than (an option)/no big deal",
    page: 42,
    key: 362,
  },
  {
    pinyin: "chǎn pǐn",
    chinese: "产品",
    meaning: "product (refers to goods)",
    page: 42,
    key: 363,
  },
  {
    pinyin: "yán zhòng",
    chinese: "严重",
    meaning:
      "serious or severe (病情bìng qíng (patient's) condition 问题wèn tí problem 情况qíng kuàng situation 后果hòu guǒ repercussion 警告jǐng gào warning 事态shì tài state of affairs 形势xíng shì situation 错误cuò wù error 疾病jí bìng disease 污染wū rǎn pollution 亏损kuī sǔn loss (of running a business) 事故shì gù accident 损坏sǔn huài damage 危害wēi hài hazard)",
    page: 42,
    key: 364,
  },
  {
    pinyin: "wù mái",
    chinese: "雾霾",
    meaning: "smog",
    page: 42,
    key: 365,
  },
  {
    pinyin: "jiāng",
    chinese: "僵",
    meaning: "stiff (of body or limb)",
    page: 42,
    key: 366,
  },
  {
    pinyin: "jiāng yìng",
    chinese: "僵硬",
    meaning: "Stiff (of body or limb) (more formal than 僵jiāng)",
    page: 42,
    key: 367,
  },
  {
    pinyin: "sāng ná",
    chinese: "桑拿",
    meaning: "suana",
    page: 42,
    key: 368,
  },
  {
    pinyin: "píngbǎn diànnǎo",
    chinese: "平板电脑",
    meaning: "tablet computer",
    page: 42,
    key: 369,
  },
  {
    pinyin: "guān shuì",
    chinese: "关税",
    meaning: "tariff (refers to customs duty)",
    page: 42,
    key: 370,
  },
  {
    pinyin: "shuì",
    chinese: "税",
    meaning: "tax",
    page: 42,
    key: 371,
  },
  {
    pinyin: "zhōu dào",
    chinese: "周到",
    meaning: "thoughtful (refers to considerate)",
    page: 42,
    key: 372,
  },
  {
    pinyin: "hóu long",
    chinese: "喉咙",
    meaning: "throat",
    page: 42,
    key: 373,
  },
  {
    pinyin: "chú wài",
    chinese: "除外",
    meaning: "to be excluded (refers to not being included)",
    page: 42,
    key: 374,
  },
  {
    pinyin: "shú/shóu",
    chinese: "熟",
    meaning: "to be familiar with/well-cooked/ripe (of fruit)",
    page: 42,
    key: 375,
  },
  {
    pinyin: "zhí de",
    chinese: "值得",
    meaning: "to be worth",
    page: 42,
    key: 376,
  },
  {
    pinyin: "bào jǐng",
    chinese: "报警",
    meaning: "to call or report the police/to sound an alarm",
    page: 42,
    key: 377,
  },
  {
    pinyin: "yù bào",
    chinese: "预报",
    meaning: "to forecast (weather)/(weather) forecast",
    page: 42,
    key: 378,
  },
  {
    pinyin: "yǒu suǒ",
    chinese: "有所",
    meaning:
      "To have some (提高tí gāo improvement 不同bù tóng difference 改变gǎi biàn to change 害怕hài pà to be scared 依靠yī kào to rely on 减少jiǎn shǎo decrease 增加zēng jiā increase 改善gǎi shàn amelioration 企图qǐ tú to intend to 隐瞒yǐn mán concealment 作为zuò wéi deed 成就chéng jiù achievement 了解liǎo jiě to know well 收获shōu huò (beneficial) gain 期待qī dài to look forward to 帮助bāng zhù help 准备zhǔn bèi preparation 增长zēng zhǎng growth 保留bǎo liú reservation 行动xíng dòng action 降低jiàng dī lowering 下降xià jiàng drop 追求zhuī qiú pursuit 发展fā zhǎn development 好转hǎo zhuǎn change for the better 不适bú shì discomfort)(formal)",
    page: 42,
    key: 379,
  },
  {
    pinyin: "àn mó",
    chinese: "按摩",
    meaning: "to massage (body)/massage",
    page: 42,
    key: 380,
  },
  {
    pinyin: "xìn búguò",
    chinese: "信不过",
    meaning: "to not trust",
    page: 42,
    key: 381,
  },
  {
    pinyin: "diàn",
    chinese: "垫",
    meaning: "to pay for (somebody and expect to be repaid later)",
    page: 42,
    key: 382,
  },
  {
    pinyin: "fáng zhǐ",
    chinese: "防止",
    meaning:
      "to prevent (中毒zhòng dú (accidental) poisoning 犯罪fàn zuì crime 腐败fǔ bài corruption 生锈shēng xiù rusting 火灾huǒ zāi fire (as a disaster) 暴力bào lì violence 浪费làng fèi waste 感染gǎn rǎn infection 重复chóng fù repetition/duplication 事故shì gù accident 损坏sǔn huài damage 氧化yǎng huà oxidation 灾难zāi nàn disaster 疾病jí bìng disease)",
    page: 42,
    key: 383,
  },
  {
    pinyin: "gēng xīn",
    chinese: "更新",
    meaning:
      "to renew or update (设备shè bèi equipment 机器jī qì machine 产品chǎn pǐn product 网站wǎng zhàn website 信息xìn xī information 系统xì tǒng system 数据shù jù data 版本bǎn běn edition 软件ruǎn jiàn software 合同hé tong contract 签证qiān zhèng visa 身份证shēnfèn zhèng Chinese identity card)",
    page: 42,
    key: 384,
  },
  {
    pinyin: "dā huà/dā shàn",
    chinese: "搭话/搭讪",
    meaning: "to start up a conversation",
    page: 42,
    key: 385,
  },
  {
    pinyin: "zhuǎn",
    chinese: "转",
    meaning: "to turn (refers to change direction)",
    page: 42,
    key: 386,
  },
  {
    pinyin: "shǐ yòng",
    chinese: "使用",
    meaning: "To use (more formal than 用yòng)/use",
    page: 42,
    key: 387,
  },
  {
    pinyin: "jǐn jí",
    chinese: "紧急",
    meaning: "Urgent (more formal than 急jí)",
    page: 42,
    key: 388,
  },
  {
    pinyin: "jǐng sè",
    chinese: "景色",
    meaning: "view (refers to visual scene)",
    page: 42,
    key: 389,
  },
  {
    pinyin: "nǚ zǐ",
    chinese: "女子",
    meaning: "Woman (more formal than 女的nǚ de)",
    page: 42,
    key: 390,
  },
  {
    pinyin: "zuò wéi",
    chinese: "作为",
    meaning: "(serve or used) as",
    page: 43,
    key: 391,
  },
  {
    pinyin: "kǒu wèi",
    chinese: "口味",
    meaning: "(food or drink) flavor/(personal) taste",
    page: 43,
    key: 392,
  },
  {
    pinyin: "gǔ tou",
    chinese: "骨头",
    meaning: "bone",
    page: 43,
    key: 393,
  },
  {
    pinyin: "chú shī",
    chinese: "厨师",
    meaning: "chef",
    page: 43,
    key: 394,
  },
  {
    pinyin: "xiáng xì",
    chinese: "详细",
    meaning: "detailed",
    page: 43,
    key: 395,
  },
  {
    pinyin: "duì huà",
    chinese: "对话",
    meaning: "dialogue",
    page: 43,
    key: 396,
  },
  {
    pinyin: "diǎn xīn",
    chinese: "点心",
    meaning: "dim sum/refreshments (refers to food)/dessert",
    page: 43,
    key: 397,
  },
  {
    pinyin: "fàn zhuō",
    chinese: "饭桌",
    meaning: "dining table",
    page: 43,
    key: 398,
  },
  {
    pinyin: "gān gà",
    chinese: "尴尬",
    meaning: "embarrassed/embarrassing",
    page: 43,
    key: 399,
  },
  {
    pinyin: "yǒu jìn",
    chinese: "有劲",
    meaning: "exciting (informal)",
    page: 43,
    key: 400,
  },
  {
    pinyin: "lǜ chá",
    chinese: "绿茶",
    meaning: "green tea",
    page: 43,
    key: 401,
  },
  {
    pinyin: "zhōng tú",
    chinese: "中途",
    meaning: "halfway",
    page: 43,
    key: 402,
  },
  {
    pinyin: "sī xià",
    chinese: "私下",
    meaning: "in private",
    page: 43,
    key: 403,
  },
  {
    pinyin: "shēng",
    chinese: "声",
    meaning: "measure word for sound or voice",
    page: 43,
    key: 404,
  },
  {
    pinyin: "nǎi chá",
    chinese: "奶茶",
    meaning: "milk tea",
    page: 43,
    key: 405,
  },
  {
    pinyin: "bú zhìyú",
    chinese: "不至于",
    meaning: "not to go so far as to",
    page: 43,
    key: 406,
  },
  {
    pinyin: "chū yú",
    chinese: "出于",
    meaning: "Out of (a reason) (formal)",
    page: 43,
    key: 407,
  },
  {
    pinyin: "zhū pái",
    chinese: "猪排",
    meaning: "pork ribs/pork chop",
    page: 43,
    key: 408,
  },
  {
    pinyin: "sè lā/shā lā",
    chinese: "色拉/沙拉",
    meaning: "salad",
    page: 43,
    key: 409,
  },
  {
    pinyin: "wéi jīn",
    chinese: "围巾",
    meaning: "scarf (around the neck)",
    page: 43,
    key: 410,
  },
  {
    pinyin: "chǎng miàn",
    chinese: "场面",
    meaning: "scene (of a particular event)",
    page: 43,
    key: 411,
  },
  {
    pinyin: "hǎi xiān",
    chinese: "海鲜",
    meaning: "seafood",
    page: 43,
    key: 412,
  },
  {
    pinyin: "zǎo wǎn/chí zǎo",
    chinese: "早晚/迟早",
    meaning: "sooner or later",
    page: 43,
    key: 413,
  },
  {
    pinyin: "lóu tī",
    chinese: "楼梯",
    meaning: "stair/stairs",
    page: 43,
    key: 414,
  },
  {
    pinyin: "tái jiē",
    chinese: "台阶",
    meaning: "step (refers to stair)/saving-face exit",
    page: 43,
    key: 415,
  },
  {
    pinyin: "duō yú",
    chinese: "多余",
    meaning: "superfluous",
    page: 43,
    key: 416,
  },
  {
    pinyin: "tián diǎn",
    chinese: "甜点",
    meaning: "sweet refreshments or dessert (refers to food)",
    page: 43,
    key: 417,
  },
  {
    pinyin: "lǜ",
    chinese: "率",
    meaning: "the rate of",
    page: 43,
    key: 418,
  },
  {
    pinyin: "bì miǎn",
    chinese: "避免",
    meaning: "to avoid (something happen)",
    page: 43,
    key: 419,
  },
  {
    pinyin: "tòng kuài",
    chinese: "痛快",
    meaning: "to be gratified",
    page: 43,
    key: 420,
  },
  {
    pinyin: "biàn guà",
    chinese: "变卦",
    meaning: "to change one's mind (negative connotation)",
    page: 43,
    key: 421,
  },
  {
    pinyin: "lái zì",
    chinese: "来自",
    meaning: "To come from (formal)",
    page: 43,
    key: 422,
  },
  {
    pinyin: "jiǎn",
    chinese: "减",
    meaning: "to decrease/to reduce",
    page: 43,
    key: 423,
  },
  {
    pinyin: "shēng",
    chinese: "生",
    meaning: "to give birth to/to be born",
    page: 43,
    key: 424,
  },
  {
    pinyin: "mán",
    chinese: "瞒",
    meaning: "to hide (a truth)",
    page: 43,
    key: 425,
  },
  {
    pinyin: "dān wù",
    chinese: "耽误",
    meaning: "to hold up (somebody or some process to slow down)",
    page: 43,
    key: 426,
  },
  {
    pinyin: "jiǎn féi",
    chinese: "减肥",
    meaning: "to lose weight",
    page: 43,
    key: 427,
  },
  {
    pinyin: "dāng miàn",
    chinese: "当面",
    meaning: "to one's face/face to face/in somebody's presence",
    page: 43,
    key: 428,
  },
  {
    pinyin: "jù jué",
    chinese: "拒绝",
    meaning: "to refuse",
    page: 43,
    key: 429,
  },
  {
    pinyin: "qù diào",
    chinese: "去掉",
    meaning: "to remove (something concrete)",
    page: 43,
    key: 430,
  },
  {
    pinyin: "chéng gōng",
    chinese: "成功",
    meaning: "to succeed (in doing something)/success/successful",
    page: 43,
    key: 431,
  },
  {
    pinyin: "pán zi",
    chinese: "盘子",
    meaning: "tray or plate (for holding food)",
    page: 43,
    key: 432,
  },
  {
    pinyin: "zuò fǎ",
    chinese: "做法",
    meaning: "way (of handling something)/method (for making something)",
    page: 43,
    key: 433,
  },
  {
    pinyin: "yì wài",
    chinese: "意外",
    meaning:
      "accident/accidental/unexpected/to be surprised (literally: out of expectation)",
    page: 44,
    key: 434,
  },
  {
    pinyin: "yínháng kǎ",
    chinese: "银行卡",
    meaning: "bank card",
    page: 44,
    key: 435,
  },
  {
    pinyin: "xìnyòng kǎ",
    chinese: "信用卡",
    meaning: "credit card",
    page: 44,
    key: 436,
  },
  {
    pinyin: "qī jiān",
    chinese: "期间",
    meaning: "During (certain time) (more formal than 的时候de shíhòu)",
    page: 44,
    key: 437,
  },
  {
    pinyin: "wài bì",
    chinese: "外币",
    meaning: "foreign currency",
    page: 44,
    key: 438,
  },
  {
    pinyin: "wǔxiū shíjiān",
    chinese: "午休时间",
    meaning: "lunch break",
    page: 44,
    key: 439,
  },
  {
    pinyin: "guóqìng jié",
    chinese: "国庆节",
    meaning: "National day",
    page: 44,
    key: 440,
  },
  {
    pinyin: "fùkuǎn fāngshì",
    chinese: "付款方式",
    meaning: "payment method",
    page: 44,
    key: 441,
  },
  {
    pinyin: "píng ān",
    chinese: "平安",
    meaning: "safe and sound",
    page: 44,
    key: 442,
  },
  {
    pinyin: "cún kuǎn",
    chinese: "存款",
    meaning: "savings deposit",
    page: 44,
    key: 443,
  },
  {
    pinyin: "guà diào",
    chinese: "挂掉",
    meaning: "to die or fail in an examation (euphemism) (informal)",
    page: 44,
    key: 444,
  },
  {
    pinyin: "xiāo shī",
    chinese: "消失",
    meaning: "to disappear",
    page: 44,
    key: 445,
  },
  {
    pinyin: "duì huàn",
    chinese: "兑换/对换",
    meaning: "To exchange (货币huò bì currency) (more formal than 换huàn)",
    page: 44,
    key: 446,
  },
  {
    pinyin: "fù kuǎn",
    chinese: "付款",
    meaning: "To pay (money) (more formal than 付钱fù qián)",
    page: 44,
    key: 447,
  },
  {
    pinyin: "cún",
    chinese: "存",
    meaning: "to save (something for use in the future )",
    page: 44,
    key: 448,
  },
  {
    pinyin: "dǎ jiāodào",
    chinese: "打交道",
    meaning: "to socialize/to have dealings with",
    page: 44,
    key: 449,
  },
  {
    pinyin: "mào mèi",
    chinese: "冒昧",
    meaning:
      "to take the liberty or make bold (to do something) (modest connotation)",
    page: 44,
    key: 450,
  },
  {
    pinyin: "zhòng jiǎng",
    chinese: "中奖",
    meaning: "to win a prize (in a lottery)",
    page: 44,
    key: 451,
  },
  {
    pinyin: "jiāng",
    chinese: "将",
    meaning:
      "Will (happen in the future)/Used when handling THE object or person (more formal than 会huì or 把bǎ)",
    page: 44,
    key: 452,
  },
  {
    pinyin: "tián",
    chinese: "填",
    meaning: "to fill (vacancy)",
    page: 45,
    key: 453,
  },
  {
    pinyin: "zuò jī",
    chinese: "座机",
    meaning: "(office or home) phone",
    page: 45,
    key: 454,
  },
  {
    pinyin: "zhù lǐ",
    chinese: "助理",
    meaning: "(personal) assistant",
    page: 45,
    key: 455,
  },
  {
    pinyin: "guì tái",
    chinese: "柜台",
    meaning: "(sales) counter",
    page: 45,
    key: 456,
  },
  {
    pinyin: "yǐ jí",
    chinese: "以及",
    meaning: "As well as (more formal than 和/跟hé/gēn)",
    page: 45,
    key: 457,
  },
  {
    pinyin: "cún zhé",
    chinese: "存折",
    meaning: "bankbook",
    page: 45,
    key: 458,
  },
  {
    pinyin: "xiāofèi zhě",
    chinese: "消费者",
    meaning: "consumer",
    page: 45,
    key: 459,
  },
  {
    pinyin: "chǔxù kǎ/jièjì kǎ",
    chinese: "储蓄卡/借记卡",
    meaning: "debit card",
    page: 45,
    key: 460,
  },
  {
    pinyin: "xìn xī",
    chinese: "信息",
    meaning: "information",
    page: 45,
    key: 461,
  },
  {
    pinyin: "jī qì",
    chinese: "机器",
    meaning: "machine",
    page: 45,
    key: 462,
  },
  {
    pinyin: "míng",
    chinese: "名",
    meaning: "Measure word for a person with certain identity (formal)",
    page: 45,
    key: 463,
  },
  {
    pinyin: "xìng míng",
    chinese: "姓名",
    meaning: "Name (of a person) (more formal than 名字míng zì)",
    page: 45,
    key: 464,
  },
  {
    pinyin: "míng chēng",
    chinese: "名称",
    meaning: "Name (of an object) (formal)",
    page: 45,
    key: 465,
  },
  {
    pinyin: "yōu huì",
    chinese: "优惠",
    meaning:
      "preferential (价格jià gé price 券quàn coupon 商品shāng pǐn commodity 条件tiáo jiàn terms (of an agreement) 活动huó dòng promotion 待遇dài yù treatment 政策zhèng cè policy)",
    page: 45,
    key: 466,
  },
  {
    pinyin: "gāi",
    chinese: "该",
    meaning:
      "The (followed by a singular noun) (more formal than 这zhè or 那nà)",
    page: 45,
    key: 467,
  },
  {
    pinyin: "xiāo fèi",
    chinese: "消费",
    meaning: "to consume (commercially)/(commercial) consumption",
    page: 45,
    key: 468,
  },
  {
    pinyin: "tián xiě",
    chinese: "填写",
    meaning: "To fill in (a form) (more formal than 填tián)",
    page: 45,
    key: 469,
  },
  {
    pinyin: "lái diàn",
    chinese: "来电",
    meaning: "To make a call here/incoming call (formal)",
    page: 45,
    key: 470,
  },
  {
    pinyin: "cāo zuò",
    chinese: "操作",
    meaning: "to operate (a machine)/(machine) operation",
    page: 45,
    key: 471,
  },
  {
    pinyin: "dǎ chā",
    chinese: "打叉",
    meaning: "to put a cross",
    page: 45,
    key: 472,
  },
  {
    pinyin: "dǎ gōu",
    chinese: "打勾",
    meaning: "to put a tick",
    page: 45,
    key: 473,
  },
  {
    pinyin: "shè zhì",
    chinese: "设置",
    meaning:
      "to set up (页面yè miàn page layout 属性shǔ xìng property 权限quán xiàn limits of authority 障碍zhàng ài obstacle 路由器lùyóu qì router 门槛mén kǎn threshold 密码mì mǎ password 机构jī gòu institution)",
    page: 45,
    key: 474,
  },
  {
    pinyin: "jiàn yì",
    chinese: "建议",
    meaning: "to suggest (refers to advising)/suggestion (refers to advice)",
    page: 45,
    key: 475,
  },
  {
    pinyin: "hé shí",
    chinese: "核实",
    meaning: "to verify (refers to check)/verification",
    page: 45,
    key: 476,
  },
  {
    pinyin: "děng dài",
    chinese: "等待",
    meaning: "To wait (more formal than 等děng)",
    page: 45,
    key: 477,
  },
  {
    pinyin: "chuāng",
    chinese: "窗",
    meaning: "window",
    page: 45,
    key: 478,
  },
  {
    pinyin: "chuāng kǒu",
    chinese: "窗口",
    meaning: "window (for service or on computer)",
    page: 45,
    key: 479,
  },
  {
    pinyin: "huóqī cúnkuǎn",
    chinese: "活期存款",
    meaning: "current deposit",
    page: 46,
    key: 480,
  },
  {
    pinyin: "dìng qī",
    chinese: "定期",
    meaning: "fixed period/at regular intervals",
    page: 46,
    key: 481,
  },
  {
    pinyin: "gōng néng",
    chinese: "功能",
    meaning: "function (of a machine, software or organ usually)",
    page: 46,
    key: 482,
  },
  {
    pinyin: "xián",
    chinese: "闲",
    meaning: "idle",
    page: 46,
    key: 483,
  },
  {
    pinyin: "lì xī",
    chinese: "利息",
    meaning: "interest (of a loan or deposit)",
    page: 46,
    key: 484,
  },
  {
    pinyin: "zhèng dàng",
    chinese: "正当",
    meaning:
      "legitimate or decent (as morally or legally correct 方法fāng fǎ method 关系guān xì relation 职业zhí yè occupation 竞争jìng zhēng competition 理由lǐ yóu reason 收入shōu rù income 途径tú jìng way (to achieve an aim) 权利quán lì rights 防卫fáng wèi defence 程序chéng xù procedure)",
    page: 46,
    key: 485,
  },
  {
    pinyin: "qiáng dà",
    chinese: "强大",
    meaning:
      "mighty or powerful (功能gōng néng function 国家guó jiā country 军队jūn duì army/troops 队伍duì wǔ troops/team 对手duì shǒu opponent 敌人dí rén enemy 意志yì zhì will 内心nèi xīn inner feeling or mind 团体tuán tǐ group (with collective goals))",
    page: 46,
    key: 486,
  },
  {
    pinyin: "mì shū",
    chinese: "秘书",
    meaning: "secretary (refers to personal assistant)",
    page: 46,
    key: 487,
  },
  {
    pinyin: "qí yú",
    chinese: "其余",
    meaning: "the rest",
    page: 46,
    key: 488,
  },
  {
    pinyin: "shòu piàn",
    chinese: "受骗",
    meaning: "to be swindled",
    page: 46,
    key: 489,
  },
  {
    pinyin: "jiāo liú",
    chinese: "交流",
    meaning: "to communicate (with each other)/communication",
    page: 46,
    key: 490,
  },
  {
    pinyin: "jìn lì",
    chinese: "尽力",
    meaning: "to do all one can",
    page: 46,
    key: 491,
  },
  {
    pinyin: "guò qī",
    chinese: "过期",
    meaning:
      "to expire or to be overdue (refers to passing the specified date)",
    page: 46,
    key: 492,
  },
  {
    pinyin: "dào qī",
    chinese: "到期",
    meaning:
      "to fall due/to expire (used before 合同hé tong contract 签证qiān zhèng visa 会员huì yuán membership 身份证shēnfèn zhèng Chinese identity card)",
    page: 46,
    key: 493,
  },
  {
    pinyin: "xiǎng xiàng",
    chinese: "想象",
    meaning: "to imagine (refers to form a mental image)/imagination",
    page: 46,
    key: 494,
  },
  {
    pinyin: "tí gōng",
    chinese: "提供",
    meaning:
      "to offer or to provide (服务fú wù service 帮助bāng zhù help 食物shí wù food 机会jī huì chance 方便fāng biàn convenience 信息xìn xī information 原料yuán liào raw material 贷款dài kuǎn loan 证据zhèng jù evidence/proof 线索xiàn suǒ lead (refers to clue) 样品yàng pǐn sample 证件zhèng jiàn credential 营养yíng yǎng nutrient 设备shè bèi equipment 资料zī liào material 情报qíng bào (official or military) intelligence 资金zī jīn money (for investment) 保障bǎo zhàng (social) guarantee 技术jì shù technology)",
    page: 46,
    key: 495,
  },
  {
    pinyin: "chū shì",
    chinese: "出示",
    meaning:
      "To show (for inspection like 身份证shēnfèn zhèng (Chinese) identity card 证件zhèng jiàn credential 门票mén piào entrance ticket 护照hù zhào passport 签证qiān zhèng visa 车票chē piào ticket 证据zhèng jù evidence/proof) (formal)",
    page: 46,
    key: 496,
  },
];
